/*
 * Network Edge APIs
 * API Documentation for NE's Beta APIs. More information about Network Edge marketplace & NE platform can be found [here](https://ecxfabric-documentation.equinix.com/hc/en-us/articles/360021809172-Enterprise-Network-Edge-Beta-Program-Introduction).
 *
 * OpenAPI spec version: General Availability
 * Contact: Network-Edge-Support@equinix.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.equinix.networkedge.model;

import java.util.Objects;

import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModelProperty;

import java.util.ArrayList;
import java.util.List;

/**
 * AgreementStatusResponse
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2019-06-20T13:45:54.773-07:00")
public class AgreementStatusResponse {
  @SerializedName("errorMessage")
  private String errorMessage = null;

  @SerializedName("gtcStatus")
  private String gtcStatus = null;

  @SerializedName("ibxInclusionListInMCA")
  private List<String> ibxInclusionListInMCA = null;

  @SerializedName("isIBXIncludedInMCA")
  private String isIBXIncludedInMCA = null;

  @SerializedName("isValid")
  private String isValid = null;

  @SerializedName("mcaStatus")
  private String mcaStatus = null;

  @SerializedName("shortFormAgrStatus")
  private String shortFormAgrStatus = null;

  @SerializedName("terms")
  private String terms = null;

  @SerializedName("termsVersionID")
  private String termsVersionID = null;

  public AgreementStatusResponse errorMessage(String errorMessage) {
    this.errorMessage = errorMessage;
    return this;
  }

   /**
   * Get errorMessage
   * @return errorMessage
  **/
  @ApiModelProperty(value = "")
  public String getErrorMessage() {
    return errorMessage;
  }

  public void setErrorMessage(String errorMessage) {
    this.errorMessage = errorMessage;
  }

  public AgreementStatusResponse gtcStatus(String gtcStatus) {
    this.gtcStatus = gtcStatus;
    return this;
  }

   /**
   * Get gtcStatus
   * @return gtcStatus
  **/
  @ApiModelProperty(value = "")
  public String getGtcStatus() {
    return gtcStatus;
  }

  public void setGtcStatus(String gtcStatus) {
    this.gtcStatus = gtcStatus;
  }

  public AgreementStatusResponse ibxInclusionListInMCA(List<String> ibxInclusionListInMCA) {
    this.ibxInclusionListInMCA = ibxInclusionListInMCA;
    return this;
  }

  public AgreementStatusResponse addIbxInclusionListInMCAItem(String ibxInclusionListInMCAItem) {
    if (this.ibxInclusionListInMCA == null) {
      this.ibxInclusionListInMCA = new ArrayList<String>();
    }
    this.ibxInclusionListInMCA.add(ibxInclusionListInMCAItem);
    return this;
  }

   /**
   * Get ibxInclusionListInMCA
   * @return ibxInclusionListInMCA
  **/
  @ApiModelProperty(value = "")
  public List<String> getIbxInclusionListInMCA() {
    return ibxInclusionListInMCA;
  }

  public void setIbxInclusionListInMCA(List<String> ibxInclusionListInMCA) {
    this.ibxInclusionListInMCA = ibxInclusionListInMCA;
  }

  public AgreementStatusResponse isIBXIncludedInMCA(String isIBXIncludedInMCA) {
    this.isIBXIncludedInMCA = isIBXIncludedInMCA;
    return this;
  }

   /**
   * Get isIBXIncludedInMCA
   * @return isIBXIncludedInMCA
  **/
  @ApiModelProperty(value = "")
  public String getIsIBXIncludedInMCA() {
    return isIBXIncludedInMCA;
  }

  public void setIsIBXIncludedInMCA(String isIBXIncludedInMCA) {
    this.isIBXIncludedInMCA = isIBXIncludedInMCA;
  }

  public AgreementStatusResponse isValid(String isValid) {
    this.isValid = isValid;
    return this;
  }

   /**
   * Get isValid
   * @return isValid
  **/
  @ApiModelProperty(value = "")
  public String getIsValid() {
    return isValid;
  }

  public void setIsValid(String isValid) {
    this.isValid = isValid;
  }

  public AgreementStatusResponse mcaStatus(String mcaStatus) {
    this.mcaStatus = mcaStatus;
    return this;
  }

   /**
   * Get mcaStatus
   * @return mcaStatus
  **/
  @ApiModelProperty(value = "")
  public String getMcaStatus() {
    return mcaStatus;
  }

  public void setMcaStatus(String mcaStatus) {
    this.mcaStatus = mcaStatus;
  }

  public AgreementStatusResponse shortFormAgrStatus(String shortFormAgrStatus) {
    this.shortFormAgrStatus = shortFormAgrStatus;
    return this;
  }

   /**
   * Get shortFormAgrStatus
   * @return shortFormAgrStatus
  **/
  @ApiModelProperty(value = "")
  public String getShortFormAgrStatus() {
    return shortFormAgrStatus;
  }

  public void setShortFormAgrStatus(String shortFormAgrStatus) {
    this.shortFormAgrStatus = shortFormAgrStatus;
  }

  public AgreementStatusResponse terms(String terms) {
    this.terms = terms;
    return this;
  }

   /**
   * Get terms
   * @return terms
  **/
  @ApiModelProperty(value = "")
  public String getTerms() {
    return terms;
  }

  public void setTerms(String terms) {
    this.terms = terms;
  }

  public AgreementStatusResponse termsVersionID(String termsVersionID) {
    this.termsVersionID = termsVersionID;
    return this;
  }

   /**
   * Get termsVersionID
   * @return termsVersionID
  **/
  @ApiModelProperty(value = "")
  public String getTermsVersionID() {
    return termsVersionID;
  }

  public void setTermsVersionID(String termsVersionID) {
    this.termsVersionID = termsVersionID;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    AgreementStatusResponse agreementStatusResponse = (AgreementStatusResponse) o;
    return Objects.equals(this.errorMessage, agreementStatusResponse.errorMessage) &&
        Objects.equals(this.gtcStatus, agreementStatusResponse.gtcStatus) &&
        Objects.equals(this.ibxInclusionListInMCA, agreementStatusResponse.ibxInclusionListInMCA) &&
        Objects.equals(this.isIBXIncludedInMCA, agreementStatusResponse.isIBXIncludedInMCA) &&
        Objects.equals(this.isValid, agreementStatusResponse.isValid) &&
        Objects.equals(this.mcaStatus, agreementStatusResponse.mcaStatus) &&
        Objects.equals(this.shortFormAgrStatus, agreementStatusResponse.shortFormAgrStatus) &&
        Objects.equals(this.terms, agreementStatusResponse.terms) &&
        Objects.equals(this.termsVersionID, agreementStatusResponse.termsVersionID);
  }

  @Override
  public int hashCode() {
    return Objects.hash(errorMessage, gtcStatus, ibxInclusionListInMCA, isIBXIncludedInMCA, isValid, mcaStatus, shortFormAgrStatus, terms, termsVersionID);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class AgreementStatusResponse {\n");
    
    sb.append("    errorMessage: ").append(toIndentedString(errorMessage)).append("\n");
    sb.append("    gtcStatus: ").append(toIndentedString(gtcStatus)).append("\n");
    sb.append("    ibxInclusionListInMCA: ").append(toIndentedString(ibxInclusionListInMCA)).append("\n");
    sb.append("    isIBXIncludedInMCA: ").append(toIndentedString(isIBXIncludedInMCA)).append("\n");
    sb.append("    isValid: ").append(toIndentedString(isValid)).append("\n");
    sb.append("    mcaStatus: ").append(toIndentedString(mcaStatus)).append("\n");
    sb.append("    shortFormAgrStatus: ").append(toIndentedString(shortFormAgrStatus)).append("\n");
    sb.append("    terms: ").append(toIndentedString(terms)).append("\n");
    sb.append("    termsVersionID: ").append(toIndentedString(termsVersionID)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

