/*
 * Network Edge APIs
 * API Documentation for NE's Beta APIs. More information about Network Edge marketplace & NE platform can be found [here](https://ecxfabric-documentation.equinix.com/hc/en-us/articles/360021809172-Enterprise-Network-Edge-Beta-Program-Introduction).
 *
 * OpenAPI spec version: General Availability
 * Contact: Network-Edge-Support@equinix.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.equinix.networkedge.model;

import java.util.Objects;

import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModelProperty;

/**
 * BgpConfigAddRequest
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2019-06-20T13:45:54.773-07:00")
public class BgpConfigAddRequest {
  @SerializedName("authenticationKey")
  private String authenticationKey = null;

  @SerializedName("connectionUUID")
  private String connectionUUID = null;

  @SerializedName("localAsn")
  private Long localAsn = null;

  @SerializedName("localIpAddress")
  private String localIpAddress = null;

  @SerializedName("remoteAsn")
  private Long remoteAsn = null;

  @SerializedName("remoteIpAddress")
  private String remoteIpAddress = null;

  public BgpConfigAddRequest authenticationKey(String authenticationKey) {
    this.authenticationKey = authenticationKey;
    return this;
  }

   /**
   * Provide a key value that you can use later to authenticate.
   * @return authenticationKey
  **/
  @ApiModelProperty(example = "pass123", value = "Provide a key value that you can use later to authenticate.")
  public String getAuthenticationKey() {
    return authenticationKey;
  }

  public void setAuthenticationKey(String authenticationKey) {
    this.authenticationKey = authenticationKey;
  }

  public BgpConfigAddRequest connectionUUID(String connectionUUID) {
    this.connectionUUID = connectionUUID;
    return this;
  }

   /**
   * UUID of the connection between the virtual device and the cloud service provider
   * @return connectionUUID
  **/
  @ApiModelProperty(example = "f79eead8-b837-41d3-9095-9b15c2c4996d", value = "UUID of the connection between the virtual device and the cloud service provider")
  public String getConnectionUUID() {
    return connectionUUID;
  }

  public void setConnectionUUID(String connectionUUID) {
    this.connectionUUID = connectionUUID;
  }

  public BgpConfigAddRequest localAsn(Long localAsn) {
    this.localAsn = localAsn;
    return this;
  }

   /**
   * Local ASN (autonomous system network). This is the ASN of the virtual device.
   * @return localAsn
  **/
  @ApiModelProperty(example = "10012", value = "Local ASN (autonomous system network). This is the ASN of the virtual device.")
  public Long getLocalAsn() {
    return localAsn;
  }

  public void setLocalAsn(Long localAsn) {
    this.localAsn = localAsn;
  }

  public BgpConfigAddRequest localIpAddress(String localIpAddress) {
    this.localIpAddress = localIpAddress;
    return this;
  }

   /**
   * Local IP Address. This is the IP address of the virtual device in CIDR format.
   * @return localIpAddress
  **/
  @ApiModelProperty(example = "100.210.1.221/30", value = "Local IP Address. This is the IP address of the virtual device in CIDR format.")
  public String getLocalIpAddress() {
    return localIpAddress;
  }

  public void setLocalIpAddress(String localIpAddress) {
    this.localIpAddress = localIpAddress;
  }

  public BgpConfigAddRequest remoteAsn(Long remoteAsn) {
    this.remoteAsn = remoteAsn;
    return this;
  }

   /**
   * Remote ASN (autonomous system network). This is the ASN of the cloud service provider.
   * @return remoteAsn
  **/
  @ApiModelProperty(example = "10013", value = "Remote ASN (autonomous system network). This is the ASN of the cloud service provider.")
  public Long getRemoteAsn() {
    return remoteAsn;
  }

  public void setRemoteAsn(Long remoteAsn) {
    this.remoteAsn = remoteAsn;
  }

  public BgpConfigAddRequest remoteIpAddress(String remoteIpAddress) {
    this.remoteIpAddress = remoteIpAddress;
    return this;
  }

   /**
   * Remote IP Address. This is the IP address of the cloud service provider.
   * @return remoteIpAddress
  **/
  @ApiModelProperty(example = "100.210.1.31", value = "Remote IP Address. This is the IP address of the cloud service provider.")
  public String getRemoteIpAddress() {
    return remoteIpAddress;
  }

  public void setRemoteIpAddress(String remoteIpAddress) {
    this.remoteIpAddress = remoteIpAddress;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    BgpConfigAddRequest bgpConfigAddRequest = (BgpConfigAddRequest) o;
    return Objects.equals(this.authenticationKey, bgpConfigAddRequest.authenticationKey) &&
        Objects.equals(this.connectionUUID, bgpConfigAddRequest.connectionUUID) &&
        Objects.equals(this.localAsn, bgpConfigAddRequest.localAsn) &&
        Objects.equals(this.localIpAddress, bgpConfigAddRequest.localIpAddress) &&
        Objects.equals(this.remoteAsn, bgpConfigAddRequest.remoteAsn) &&
        Objects.equals(this.remoteIpAddress, bgpConfigAddRequest.remoteIpAddress);
  }

  @Override
  public int hashCode() {
    return Objects.hash(authenticationKey, connectionUUID, localAsn, localIpAddress, remoteAsn, remoteIpAddress);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class BgpConfigAddRequest {\n");
    
    sb.append("    authenticationKey: ").append(toIndentedString(authenticationKey)).append("\n");
    sb.append("    connectionUUID: ").append(toIndentedString(connectionUUID)).append("\n");
    sb.append("    localAsn: ").append(toIndentedString(localAsn)).append("\n");
    sb.append("    localIpAddress: ").append(toIndentedString(localIpAddress)).append("\n");
    sb.append("    remoteAsn: ").append(toIndentedString(remoteAsn)).append("\n");
    sb.append("    remoteIpAddress: ").append(toIndentedString(remoteIpAddress)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

