/*
 * Network Edge APIs
 * API Documentation for NE's Beta APIs. More information about Network Edge marketplace & NE platform can be found [here](https://ecxfabric-documentation.equinix.com/hc/en-us/articles/360021809172-Enterprise-Network-Edge-Beta-Program-Introduction).
 *
 * OpenAPI spec version: General Availability
 * Contact: Network-Edge-Support@equinix.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.equinix.networkedge.model;

import java.util.Objects;

import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModelProperty;
import com.equinix.networkedge.model.BgpConnectionInfo;

/**
 * BgpConnectionInfo
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2019-06-20T13:45:54.773-07:00")
public class BgpConnectionInfo {
  @SerializedName("bgpStatus")
  private String bgpStatus = null;

  @SerializedName("isPrimary")
  private Boolean isPrimary = null;

  @SerializedName("metro")
  private String metro = null;

  @SerializedName("name")
  private String name = null;

  @SerializedName("providerStatus")
  private String providerStatus = null;

  @SerializedName("redundantConnection")
  private BgpConnectionInfo redundantConnection = null;

  @SerializedName("redundantUUID")
  private String redundantUUID = null;

  @SerializedName("sellerOrganizationName")
  private String sellerOrganizationName = null;

  @SerializedName("status")
  private String status = null;

  @SerializedName("uuid")
  private String uuid = null;

  public BgpConnectionInfo bgpStatus(String bgpStatus) {
    this.bgpStatus = bgpStatus;
    return this;
  }

   /**
   * Get bgpStatus
   * @return bgpStatus
  **/
  @ApiModelProperty(value = "")
  public String getBgpStatus() {
    return bgpStatus;
  }

  public void setBgpStatus(String bgpStatus) {
    this.bgpStatus = bgpStatus;
  }

  public BgpConnectionInfo isPrimary(Boolean isPrimary) {
    this.isPrimary = isPrimary;
    return this;
  }

   /**
   * Get isPrimary
   * @return isPrimary
  **/
  @ApiModelProperty(value = "")
  public Boolean isIsPrimary() {
    return isPrimary;
  }

  public void setIsPrimary(Boolean isPrimary) {
    this.isPrimary = isPrimary;
  }

  public BgpConnectionInfo metro(String metro) {
    this.metro = metro;
    return this;
  }

   /**
   * Get metro
   * @return metro
  **/
  @ApiModelProperty(value = "")
  public String getMetro() {
    return metro;
  }

  public void setMetro(String metro) {
    this.metro = metro;
  }

  public BgpConnectionInfo name(String name) {
    this.name = name;
    return this;
  }

   /**
   * Get name
   * @return name
  **/
  @ApiModelProperty(value = "")
  public String getName() {
    return name;
  }

  public void setName(String name) {
    this.name = name;
  }

  public BgpConnectionInfo providerStatus(String providerStatus) {
    this.providerStatus = providerStatus;
    return this;
  }

   /**
   * Get providerStatus
   * @return providerStatus
  **/
  @ApiModelProperty(value = "")
  public String getProviderStatus() {
    return providerStatus;
  }

  public void setProviderStatus(String providerStatus) {
    this.providerStatus = providerStatus;
  }

  public BgpConnectionInfo redundantConnection(BgpConnectionInfo redundantConnection) {
    this.redundantConnection = redundantConnection;
    return this;
  }

   /**
   * Get redundantConnection
   * @return redundantConnection
  **/
  @ApiModelProperty(value = "")
  public BgpConnectionInfo getRedundantConnection() {
    return redundantConnection;
  }

  public void setRedundantConnection(BgpConnectionInfo redundantConnection) {
    this.redundantConnection = redundantConnection;
  }

  public BgpConnectionInfo redundantUUID(String redundantUUID) {
    this.redundantUUID = redundantUUID;
    return this;
  }

   /**
   * Get redundantUUID
   * @return redundantUUID
  **/
  @ApiModelProperty(value = "")
  public String getRedundantUUID() {
    return redundantUUID;
  }

  public void setRedundantUUID(String redundantUUID) {
    this.redundantUUID = redundantUUID;
  }

  public BgpConnectionInfo sellerOrganizationName(String sellerOrganizationName) {
    this.sellerOrganizationName = sellerOrganizationName;
    return this;
  }

   /**
   * Get sellerOrganizationName
   * @return sellerOrganizationName
  **/
  @ApiModelProperty(value = "")
  public String getSellerOrganizationName() {
    return sellerOrganizationName;
  }

  public void setSellerOrganizationName(String sellerOrganizationName) {
    this.sellerOrganizationName = sellerOrganizationName;
  }

  public BgpConnectionInfo status(String status) {
    this.status = status;
    return this;
  }

   /**
   * Get status
   * @return status
  **/
  @ApiModelProperty(value = "")
  public String getStatus() {
    return status;
  }

  public void setStatus(String status) {
    this.status = status;
  }

  public BgpConnectionInfo uuid(String uuid) {
    this.uuid = uuid;
    return this;
  }

   /**
   * Get uuid
   * @return uuid
  **/
  @ApiModelProperty(value = "")
  public String getUuid() {
    return uuid;
  }

  public void setUuid(String uuid) {
    this.uuid = uuid;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    BgpConnectionInfo bgpConnectionInfo = (BgpConnectionInfo) o;
    return Objects.equals(this.bgpStatus, bgpConnectionInfo.bgpStatus) &&
        Objects.equals(this.isPrimary, bgpConnectionInfo.isPrimary) &&
        Objects.equals(this.metro, bgpConnectionInfo.metro) &&
        Objects.equals(this.name, bgpConnectionInfo.name) &&
        Objects.equals(this.providerStatus, bgpConnectionInfo.providerStatus) &&
        Objects.equals(this.redundantConnection, bgpConnectionInfo.redundantConnection) &&
        Objects.equals(this.redundantUUID, bgpConnectionInfo.redundantUUID) &&
        Objects.equals(this.sellerOrganizationName, bgpConnectionInfo.sellerOrganizationName) &&
        Objects.equals(this.status, bgpConnectionInfo.status) &&
        Objects.equals(this.uuid, bgpConnectionInfo.uuid);
  }

  @Override
  public int hashCode() {
    return Objects.hash(bgpStatus, isPrimary, metro, name, providerStatus, redundantConnection, redundantUUID, sellerOrganizationName, status, uuid);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class BgpConnectionInfo {\n");
    
    sb.append("    bgpStatus: ").append(toIndentedString(bgpStatus)).append("\n");
    sb.append("    isPrimary: ").append(toIndentedString(isPrimary)).append("\n");
    sb.append("    metro: ").append(toIndentedString(metro)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    providerStatus: ").append(toIndentedString(providerStatus)).append("\n");
    sb.append("    redundantConnection: ").append(toIndentedString(redundantConnection)).append("\n");
    sb.append("    redundantUUID: ").append(toIndentedString(redundantUUID)).append("\n");
    sb.append("    sellerOrganizationName: ").append(toIndentedString(sellerOrganizationName)).append("\n");
    sb.append("    status: ").append(toIndentedString(status)).append("\n");
    sb.append("    uuid: ").append(toIndentedString(uuid)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

