/*
 * Network Edge APIs
 * API Documentation for NE's Beta APIs. More information about Network Edge marketplace & NE platform can be found [here](https://ecxfabric-documentation.equinix.com/hc/en-us/articles/360021809172-Enterprise-Network-Edge-Beta-Program-Introduction).
 *
 * OpenAPI spec version: General Availability
 * Contact: Network-Edge-Support@equinix.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */


package com.equinix.networkedge.model;

import java.util.Objects;

import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModelProperty;

/**
 * CompositePriceResponse
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2019-06-20T13:45:54.773-07:00")
public class CompositePriceResponse {
  @SerializedName("primary")
  private PriceResponse primary = null;

  @SerializedName("secondary")
  private PriceResponse secondary = null;

  @SerializedName("termLength")
  private String termLength = null;

  public CompositePriceResponse primary(PriceResponse primary) {
    this.primary = primary;
    return this;
  }

   /**
   * Get primary
   * @return primary
  **/
  @ApiModelProperty(value = "")
  public PriceResponse getPrimary() {
    return primary;
  }

  public void setPrimary(PriceResponse primary) {
    this.primary = primary;
  }

  public CompositePriceResponse secondary(PriceResponse secondary) {
    this.secondary = secondary;
    return this;
  }

   /**
   * Get secondary
   * @return secondary
  **/
  @ApiModelProperty(value = "")
  public PriceResponse getSecondary() {
    return secondary;
  }

  public void setSecondary(PriceResponse secondary) {
    this.secondary = secondary;
  }

  public CompositePriceResponse termLength(String termLength) {
    this.termLength = termLength;
    return this;
  }

   /**
   * Get termLength
   * @return termLength
  **/
  @ApiModelProperty(example = "24", value = "")
  public String getTermLength() {
    return termLength;
  }

  public void setTermLength(String termLength) {
    this.termLength = termLength;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    CompositePriceResponse compositePriceResponse = (CompositePriceResponse) o;
    return Objects.equals(this.primary, compositePriceResponse.primary) &&
        Objects.equals(this.secondary, compositePriceResponse.secondary) &&
        Objects.equals(this.termLength, compositePriceResponse.termLength);
  }

  @Override
  public int hashCode() {
    return Objects.hash(primary, secondary, termLength);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class CompositePriceResponse {\n");
    
    sb.append("    primary: ").append(toIndentedString(primary)).append("\n");
    sb.append("    secondary: ").append(toIndentedString(secondary)).append("\n");
    sb.append("    termLength: ").append(toIndentedString(termLength)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

