/*
 * Network Edge APIs
 * API Documentation for NE's Beta APIs. More information about Network Edge marketplace & NE platform can be found [here](https://ecxfabric-documentation.equinix.com/hc/en-us/articles/360021809172-Enterprise-Network-Edge-Beta-Program-Introduction).
 *
 * OpenAPI spec version: General Availability
 * Contact: Network-Edge-Support@equinix.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.equinix.networkedge.model;

import java.util.Objects;

import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModelProperty;

/**
 * DeleteConnectionResponse
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2019-06-20T13:45:54.773-07:00")
public class DeleteConnectionResponse {
  @SerializedName("message")
  private String message = null;

  @SerializedName("primaryConnectionId")
  private String primaryConnectionId = null;

  public DeleteConnectionResponse message(String message) {
    this.message = message;
    return this;
  }

   /**
   * Get message
   * @return message
  **/
  @ApiModelProperty(example = "Message", value = "")
  public String getMessage() {
    return message;
  }

  public void setMessage(String message) {
    this.message = message;
  }

  public DeleteConnectionResponse primaryConnectionId(String primaryConnectionId) {
    this.primaryConnectionId = primaryConnectionId;
    return this;
  }

   /**
   * Get primaryConnectionId
   * @return primaryConnectionId
  **/
  @ApiModelProperty(example = "xxxxx191-xx70-xxxx-xx04-xxxxxxxa37xx", value = "")
  public String getPrimaryConnectionId() {
    return primaryConnectionId;
  }

  public void setPrimaryConnectionId(String primaryConnectionId) {
    this.primaryConnectionId = primaryConnectionId;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    DeleteConnectionResponse deleteConnectionResponse = (DeleteConnectionResponse) o;
    return Objects.equals(this.message, deleteConnectionResponse.message) &&
        Objects.equals(this.primaryConnectionId, deleteConnectionResponse.primaryConnectionId);
  }

  @Override
  public int hashCode() {
    return Objects.hash(message, primaryConnectionId);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class DeleteConnectionResponse {\n");
    
    sb.append("    message: ").append(toIndentedString(message)).append("\n");
    sb.append("    primaryConnectionId: ").append(toIndentedString(primaryConnectionId)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

