/*
 * Network Edge APIs
 * API Documentation for NE's Beta APIs. More information about Network Edge marketplace & NE platform can be found [here](https://ecxfabric-documentation.equinix.com/hc/en-us/articles/360021809172-Enterprise-Network-Edge-Beta-Program-Introduction).
 *
 * OpenAPI spec version: General Availability
 * Contact: Network-Edge-Support@equinix.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.equinix.networkedge.model;

import java.util.Objects;

import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModelProperty;

import java.util.ArrayList;
import java.util.List;

/**
 * GetBuyerConResContent
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2019-06-20T13:45:54.773-07:00")
public class GetBuyerConResContent {
  @SerializedName("asideEncapsulation")
  private String asideEncapsulation = null;

  @SerializedName("authorizationKey")
  private String authorizationKey = null;

  @SerializedName("billingTier")
  private String billingTier = null;

  @SerializedName("buyerOrganizationName")
  private String buyerOrganizationName = null;

  @SerializedName("createdBy")
  private String createdBy = null;

  @SerializedName("createdByEmail")
  private String createdByEmail = null;

  @SerializedName("createdByFullName")
  private String createdByFullName = null;

  @SerializedName("createdDate")
  private String createdDate = null;

  @SerializedName("lastUpdatedBy")
  private String lastUpdatedBy = null;

  @SerializedName("lastUpdatedByEmail")
  private String lastUpdatedByEmail = null;

  @SerializedName("lastUpdatedByFullName")
  private String lastUpdatedByFullName = null;

  @SerializedName("lastUpdatedDate")
  private String lastUpdatedDate = null;

  @SerializedName("metroCode")
  private String metroCode = null;

  @SerializedName("metroDescription")
  private String metroDescription = null;

  @SerializedName("name")
  private String name = null;

  @SerializedName("namedTag")
  private String namedTag = null;

  @SerializedName("notifications")
  private List<String> notifications = null;

  @SerializedName("virtualDeviceUUID")
  private String virtualDeviceUUID = null;

  @SerializedName("private")
  private Boolean _private = null;

  @SerializedName("purchaseOrderNumber")
  private String purchaseOrderNumber = null;

  @SerializedName("redundancyGroup")
  private String redundancyGroup = null;

  @SerializedName("redundancyType")
  private String redundancyType = null;

  @SerializedName("redundantUUID")
  private String redundantUUID = null;

  @SerializedName("remote")
  private Boolean remote = null;

  @SerializedName("self")
  private Boolean self = null;

  @SerializedName("sellerMetroCode")
  private String sellerMetroCode = null;

  @SerializedName("sellerMetroDescription")
  private String sellerMetroDescription = null;

  @SerializedName("sellerOrganizationName")
  private String sellerOrganizationName = null;

  @SerializedName("sellerServiceName")
  private String sellerServiceName = null;

  @SerializedName("sellerServiceUUID")
  private String sellerServiceUUID = null;

  @SerializedName("speed")
  private Integer speed = null;

  @SerializedName("speedUnit")
  private String speedUnit = null;

  @SerializedName("providerStatus")
  private String providerStatus = null;

  @SerializedName("status")
  private String status = null;

  @SerializedName("uuid")
  private String uuid = null;

  @SerializedName("vlanSTag")
  private Integer vlanSTag = null;

  @SerializedName("zSidePortName")
  private String zSidePortName = null;

  @SerializedName("zSidePortUUID")
  private String zSidePortUUID = null;

  @SerializedName("zSideVlanCTag")
  private Integer zSideVlanCTag = null;

  @SerializedName("zSideVlanSTag")
  private Integer zSideVlanSTag = null;

  public GetBuyerConResContent asideEncapsulation(String asideEncapsulation) {
    this.asideEncapsulation = asideEncapsulation;
    return this;
  }

   /**
   * Get asideEncapsulation
   * @return asideEncapsulation
  **/
  @ApiModelProperty(example = "dot1q", value = "")
  public String getAsideEncapsulation() {
    return asideEncapsulation;
  }

  public void setAsideEncapsulation(String asideEncapsulation) {
    this.asideEncapsulation = asideEncapsulation;
  }

  public GetBuyerConResContent authorizationKey(String authorizationKey) {
    this.authorizationKey = authorizationKey;
    return this;
  }

   /**
   * Get authorizationKey
   * @return authorizationKey
  **/
  @ApiModelProperty(example = "xxxxx191-xx70-xxxx-xx04-xxxxxxxa37xx", value = "")
  public String getAuthorizationKey() {
    return authorizationKey;
  }

  public void setAuthorizationKey(String authorizationKey) {
    this.authorizationKey = authorizationKey;
  }

  public GetBuyerConResContent billingTier(String billingTier) {
    this.billingTier = billingTier;
    return this;
  }

   /**
   * Get billingTier
   * @return billingTier
  **/
  @ApiModelProperty(example = "Up to 50 MB", value = "")
  public String getBillingTier() {
    return billingTier;
  }

  public void setBillingTier(String billingTier) {
    this.billingTier = billingTier;
  }

  public GetBuyerConResContent buyerOrganizationName(String buyerOrganizationName) {
    this.buyerOrganizationName = buyerOrganizationName;
    return this;
  }

   /**
   * Get buyerOrganizationName
   * @return buyerOrganizationName
  **/
  @ApiModelProperty(example = "Sandbox User", value = "")
  public String getBuyerOrganizationName() {
    return buyerOrganizationName;
  }

  public void setBuyerOrganizationName(String buyerOrganizationName) {
    this.buyerOrganizationName = buyerOrganizationName;
  }

  public GetBuyerConResContent createdBy(String createdBy) {
    this.createdBy = createdBy;
    return this;
  }

   /**
   * Get createdBy
   * @return createdBy
  **/
  @ApiModelProperty(example = "Sandbox User", value = "")
  public String getCreatedBy() {
    return createdBy;
  }

  public void setCreatedBy(String createdBy) {
    this.createdBy = createdBy;
  }

  public GetBuyerConResContent createdByEmail(String createdByEmail) {
    this.createdByEmail = createdByEmail;
    return this;
  }

   /**
   * Get createdByEmail
   * @return createdByEmail
  **/
  @ApiModelProperty(example = "sandboxuser@example-company.com", value = "")
  public String getCreatedByEmail() {
    return createdByEmail;
  }

  public void setCreatedByEmail(String createdByEmail) {
    this.createdByEmail = createdByEmail;
  }

  public GetBuyerConResContent createdByFullName(String createdByFullName) {
    this.createdByFullName = createdByFullName;
    return this;
  }

   /**
   * Get createdByFullName
   * @return createdByFullName
  **/
  @ApiModelProperty(example = "Sandbox USER", value = "")
  public String getCreatedByFullName() {
    return createdByFullName;
  }

  public void setCreatedByFullName(String createdByFullName) {
    this.createdByFullName = createdByFullName;
  }

  public GetBuyerConResContent createdDate(String createdDate) {
    this.createdDate = createdDate;
    return this;
  }

   /**
   * Get createdDate
   * @return createdDate
  **/
  @ApiModelProperty(example = "2018-04-12T18:05:24.167Z", value = "")
  public String getCreatedDate() {
    return createdDate;
  }

  public void setCreatedDate(String createdDate) {
    this.createdDate = createdDate;
  }

  public GetBuyerConResContent lastUpdatedBy(String lastUpdatedBy) {
    this.lastUpdatedBy = lastUpdatedBy;
    return this;
  }

   /**
   * Get lastUpdatedBy
   * @return lastUpdatedBy
  **/
  @ApiModelProperty(example = "Sandbox User", value = "")
  public String getLastUpdatedBy() {
    return lastUpdatedBy;
  }

  public void setLastUpdatedBy(String lastUpdatedBy) {
    this.lastUpdatedBy = lastUpdatedBy;
  }

  public GetBuyerConResContent lastUpdatedByEmail(String lastUpdatedByEmail) {
    this.lastUpdatedByEmail = lastUpdatedByEmail;
    return this;
  }

   /**
   * Get lastUpdatedByEmail
   * @return lastUpdatedByEmail
  **/
  @ApiModelProperty(example = "sandboxuser@example-company.com", value = "")
  public String getLastUpdatedByEmail() {
    return lastUpdatedByEmail;
  }

  public void setLastUpdatedByEmail(String lastUpdatedByEmail) {
    this.lastUpdatedByEmail = lastUpdatedByEmail;
  }

  public GetBuyerConResContent lastUpdatedByFullName(String lastUpdatedByFullName) {
    this.lastUpdatedByFullName = lastUpdatedByFullName;
    return this;
  }

   /**
   * Get lastUpdatedByFullName
   * @return lastUpdatedByFullName
  **/
  @ApiModelProperty(example = "Sandbox User", value = "")
  public String getLastUpdatedByFullName() {
    return lastUpdatedByFullName;
  }

  public void setLastUpdatedByFullName(String lastUpdatedByFullName) {
    this.lastUpdatedByFullName = lastUpdatedByFullName;
  }

  public GetBuyerConResContent lastUpdatedDate(String lastUpdatedDate) {
    this.lastUpdatedDate = lastUpdatedDate;
    return this;
  }

   /**
   * Get lastUpdatedDate
   * @return lastUpdatedDate
  **/
  @ApiModelProperty(example = "2018-04-12T17:13:53.031Z", value = "")
  public String getLastUpdatedDate() {
    return lastUpdatedDate;
  }

  public void setLastUpdatedDate(String lastUpdatedDate) {
    this.lastUpdatedDate = lastUpdatedDate;
  }

  public GetBuyerConResContent metroCode(String metroCode) {
    this.metroCode = metroCode;
    return this;
  }

   /**
   * Get metroCode
   * @return metroCode
  **/
  @ApiModelProperty(example = "CH", value = "")
  public String getMetroCode() {
    return metroCode;
  }

  public void setMetroCode(String metroCode) {
    this.metroCode = metroCode;
  }

  public GetBuyerConResContent metroDescription(String metroDescription) {
    this.metroDescription = metroDescription;
    return this;
  }

   /**
   * Get metroDescription
   * @return metroDescription
  **/
  @ApiModelProperty(example = "Chicago", value = "")
  public String getMetroDescription() {
    return metroDescription;
  }

  public void setMetroDescription(String metroDescription) {
    this.metroDescription = metroDescription;
  }

  public GetBuyerConResContent name(String name) {
    this.name = name;
    return this;
  }

   /**
   * Get name
   * @return name
  **/
  @ApiModelProperty(example = "Sandbox 001S", value = "")
  public String getName() {
    return name;
  }

  public void setName(String name) {
    this.name = name;
  }

  public GetBuyerConResContent namedTag(String namedTag) {
    this.namedTag = namedTag;
    return this;
  }

   /**
   * Get namedTag
   * @return namedTag
  **/
  @ApiModelProperty(value = "")
  public String getNamedTag() {
    return namedTag;
  }

  public void setNamedTag(String namedTag) {
    this.namedTag = namedTag;
  }

  public GetBuyerConResContent notifications(List<String> notifications) {
    this.notifications = notifications;
    return this;
  }

  public GetBuyerConResContent addNotificationsItem(String notificationsItem) {
    if (this.notifications == null) {
      this.notifications = new ArrayList<String>();
    }
    this.notifications.add(notificationsItem);
    return this;
  }

   /**
   * Get notifications
   * @return notifications
  **/
  @ApiModelProperty(value = "")
  public List<String> getNotifications() {
    return notifications;
  }

  public void setNotifications(List<String> notifications) {
    this.notifications = notifications;
  }

  public GetBuyerConResContent virtualDeviceUUID(String virtualDeviceUUID) {
    this.virtualDeviceUUID = virtualDeviceUUID;
    return this;
  }

   /**
   * Get virtualDeviceUUID
   * @return virtualDeviceUUID
  **/
  @ApiModelProperty(example = "xxxxx191-xx70-xxxx-xx04-xxxxxxxa37xx", value = "")
  public String getVirtualDeviceUUID() {
    return virtualDeviceUUID;
  }

  public void setVirtualDeviceUUID(String virtualDeviceUUID) {
    this.virtualDeviceUUID = virtualDeviceUUID;
  }

  public GetBuyerConResContent _private(Boolean _private) {
    this._private = _private;
    return this;
  }

   /**
   * Get _private
   * @return _private
  **/
  @ApiModelProperty(example = "false", value = "")
  public Boolean isPrivate() {
    return _private;
  }

  public void setPrivate(Boolean _private) {
    this._private = _private;
  }

  public GetBuyerConResContent purchaseOrderNumber(String purchaseOrderNumber) {
    this.purchaseOrderNumber = purchaseOrderNumber;
    return this;
  }

   /**
   * Get purchaseOrderNumber
   * @return purchaseOrderNumber
  **/
  @ApiModelProperty(example = "111", value = "")
  public String getPurchaseOrderNumber() {
    return purchaseOrderNumber;
  }

  public void setPurchaseOrderNumber(String purchaseOrderNumber) {
    this.purchaseOrderNumber = purchaseOrderNumber;
  }

  public GetBuyerConResContent redundancyGroup(String redundancyGroup) {
    this.redundancyGroup = redundancyGroup;
    return this;
  }

   /**
   * Get redundancyGroup
   * @return redundancyGroup
  **/
  @ApiModelProperty(example = "xxxxx191-xx70-xxxx-xx04-xxxxxxxa37xx", value = "")
  public String getRedundancyGroup() {
    return redundancyGroup;
  }

  public void setRedundancyGroup(String redundancyGroup) {
    this.redundancyGroup = redundancyGroup;
  }

  public GetBuyerConResContent redundancyType(String redundancyType) {
    this.redundancyType = redundancyType;
    return this;
  }

   /**
   * Get redundancyType
   * @return redundancyType
  **/
  @ApiModelProperty(example = "secondary", value = "")
  public String getRedundancyType() {
    return redundancyType;
  }

  public void setRedundancyType(String redundancyType) {
    this.redundancyType = redundancyType;
  }

  public GetBuyerConResContent redundantUUID(String redundantUUID) {
    this.redundantUUID = redundantUUID;
    return this;
  }

   /**
   * Get redundantUUID
   * @return redundantUUID
  **/
  @ApiModelProperty(example = "xxxxx191-xx70-xxxx-xx04-xxxxxxxa37xx", value = "")
  public String getRedundantUUID() {
    return redundantUUID;
  }

  public void setRedundantUUID(String redundantUUID) {
    this.redundantUUID = redundantUUID;
  }

  public GetBuyerConResContent remote(Boolean remote) {
    this.remote = remote;
    return this;
  }

   /**
   * Get remote
   * @return remote
  **/
  @ApiModelProperty(example = "true", value = "")
  public Boolean isRemote() {
    return remote;
  }

  public void setRemote(Boolean remote) {
    this.remote = remote;
  }

  public GetBuyerConResContent self(Boolean self) {
    this.self = self;
    return this;
  }

   /**
   * Get self
   * @return self
  **/
  @ApiModelProperty(example = "false", value = "")
  public Boolean isSelf() {
    return self;
  }

  public void setSelf(Boolean self) {
    this.self = self;
  }

  public GetBuyerConResContent sellerMetroCode(String sellerMetroCode) {
    this.sellerMetroCode = sellerMetroCode;
    return this;
  }

   /**
   * Get sellerMetroCode
   * @return sellerMetroCode
  **/
  @ApiModelProperty(example = "Sv", value = "")
  public String getSellerMetroCode() {
    return sellerMetroCode;
  }

  public void setSellerMetroCode(String sellerMetroCode) {
    this.sellerMetroCode = sellerMetroCode;
  }

  public GetBuyerConResContent sellerMetroDescription(String sellerMetroDescription) {
    this.sellerMetroDescription = sellerMetroDescription;
    return this;
  }

   /**
   * Get sellerMetroDescription
   * @return sellerMetroDescription
  **/
  @ApiModelProperty(example = "Silicon Valley", value = "")
  public String getSellerMetroDescription() {
    return sellerMetroDescription;
  }

  public void setSellerMetroDescription(String sellerMetroDescription) {
    this.sellerMetroDescription = sellerMetroDescription;
  }

  public GetBuyerConResContent sellerOrganizationName(String sellerOrganizationName) {
    this.sellerOrganizationName = sellerOrganizationName;
    return this;
  }

   /**
   * Get sellerOrganizationName
   * @return sellerOrganizationName
  **/
  @ApiModelProperty(example = "sit-001", value = "")
  public String getSellerOrganizationName() {
    return sellerOrganizationName;
  }

  public void setSellerOrganizationName(String sellerOrganizationName) {
    this.sellerOrganizationName = sellerOrganizationName;
  }

  public GetBuyerConResContent sellerServiceName(String sellerServiceName) {
    this.sellerServiceName = sellerServiceName;
    return this;
  }

   /**
   * Get sellerServiceName
   * @return sellerServiceName
  **/
  @ApiModelProperty(example = "Azure Express Route", value = "")
  public String getSellerServiceName() {
    return sellerServiceName;
  }

  public void setSellerServiceName(String sellerServiceName) {
    this.sellerServiceName = sellerServiceName;
  }

  public GetBuyerConResContent sellerServiceUUID(String sellerServiceUUID) {
    this.sellerServiceUUID = sellerServiceUUID;
    return this;
  }

   /**
   * Get sellerServiceUUID
   * @return sellerServiceUUID
  **/
  @ApiModelProperty(example = "xxxxx191-xx70-xxxx-xx04-xxxxxxxa37xx", value = "")
  public String getSellerServiceUUID() {
    return sellerServiceUUID;
  }

  public void setSellerServiceUUID(String sellerServiceUUID) {
    this.sellerServiceUUID = sellerServiceUUID;
  }

  public GetBuyerConResContent speed(Integer speed) {
    this.speed = speed;
    return this;
  }

   /**
   * Get speed
   * @return speed
  **/
  @ApiModelProperty(example = "50", value = "")
  public Integer getSpeed() {
    return speed;
  }

  public void setSpeed(Integer speed) {
    this.speed = speed;
  }

  public GetBuyerConResContent speedUnit(String speedUnit) {
    this.speedUnit = speedUnit;
    return this;
  }

   /**
   * Get speedUnit
   * @return speedUnit
  **/
  @ApiModelProperty(example = "MB", value = "")
  public String getSpeedUnit() {
    return speedUnit;
  }

  public void setSpeedUnit(String speedUnit) {
    this.speedUnit = speedUnit;
  }

  public GetBuyerConResContent providerStatus(String providerStatus) {
    this.providerStatus = providerStatus;
    return this;
  }

   /**
   * Get providerStatus
   * @return providerStatus
  **/
  @ApiModelProperty(example = "PROVISIONED", value = "")
  public String getProviderStatus() {
    return providerStatus;
  }

  public void setProviderStatus(String providerStatus) {
    this.providerStatus = providerStatus;
  }

  public GetBuyerConResContent status(String status) {
    this.status = status;
    return this;
  }

   /**
   * Get status
   * @return status
  **/
  @ApiModelProperty(example = "PROVISIONED", value = "")
  public String getStatus() {
    return status;
  }

  public void setStatus(String status) {
    this.status = status;
  }

  public GetBuyerConResContent uuid(String uuid) {
    this.uuid = uuid;
    return this;
  }

   /**
   * Get uuid
   * @return uuid
  **/
  @ApiModelProperty(example = "xxxxx191-xx70-xxxx-xx04-xxxxxxxa37xx", value = "")
  public String getUuid() {
    return uuid;
  }

  public void setUuid(String uuid) {
    this.uuid = uuid;
  }

  public GetBuyerConResContent vlanSTag(Integer vlanSTag) {
    this.vlanSTag = vlanSTag;
    return this;
  }

   /**
   * Get vlanSTag
   * @return vlanSTag
  **/
  @ApiModelProperty(example = "11", value = "")
  public Integer getVlanSTag() {
    return vlanSTag;
  }

  public void setVlanSTag(Integer vlanSTag) {
    this.vlanSTag = vlanSTag;
  }

  public GetBuyerConResContent zSidePortName(String zSidePortName) {
    this.zSidePortName = zSidePortName;
    return this;
  }

   /**
   * Get zSidePortName
   * @return zSidePortName
  **/
  @ApiModelProperty(example = "SJC-TEST-TEST-06TES-CIS-5-TES-A", value = "")
  public String getZSidePortName() {
    return zSidePortName;
  }

  public void setZSidePortName(String zSidePortName) {
    this.zSidePortName = zSidePortName;
  }

  public GetBuyerConResContent zSidePortUUID(String zSidePortUUID) {
    this.zSidePortUUID = zSidePortUUID;
    return this;
  }

   /**
   * Get zSidePortUUID
   * @return zSidePortUUID
  **/
  @ApiModelProperty(example = "xxxxx191-xx70-xxxx-xx04-xxxxxxxa37xx", value = "")
  public String getZSidePortUUID() {
    return zSidePortUUID;
  }

  public void setZSidePortUUID(String zSidePortUUID) {
    this.zSidePortUUID = zSidePortUUID;
  }

  public GetBuyerConResContent zSideVlanCTag(Integer zSideVlanCTag) {
    this.zSideVlanCTag = zSideVlanCTag;
    return this;
  }

   /**
   * Get zSideVlanCTag
   * @return zSideVlanCTag
  **/
  @ApiModelProperty(example = "201", value = "")
  public Integer getZSideVlanCTag() {
    return zSideVlanCTag;
  }

  public void setZSideVlanCTag(Integer zSideVlanCTag) {
    this.zSideVlanCTag = zSideVlanCTag;
  }

  public GetBuyerConResContent zSideVlanSTag(Integer zSideVlanSTag) {
    this.zSideVlanSTag = zSideVlanSTag;
    return this;
  }

   /**
   * Get zSideVlanSTag
   * @return zSideVlanSTag
  **/
  @ApiModelProperty(example = "11", value = "")
  public Integer getZSideVlanSTag() {
    return zSideVlanSTag;
  }

  public void setZSideVlanSTag(Integer zSideVlanSTag) {
    this.zSideVlanSTag = zSideVlanSTag;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    GetBuyerConResContent getBuyerConResContent = (GetBuyerConResContent) o;
    return Objects.equals(this.asideEncapsulation, getBuyerConResContent.asideEncapsulation) &&
        Objects.equals(this.authorizationKey, getBuyerConResContent.authorizationKey) &&
        Objects.equals(this.billingTier, getBuyerConResContent.billingTier) &&
        Objects.equals(this.buyerOrganizationName, getBuyerConResContent.buyerOrganizationName) &&
        Objects.equals(this.createdBy, getBuyerConResContent.createdBy) &&
        Objects.equals(this.createdByEmail, getBuyerConResContent.createdByEmail) &&
        Objects.equals(this.createdByFullName, getBuyerConResContent.createdByFullName) &&
        Objects.equals(this.createdDate, getBuyerConResContent.createdDate) &&
        Objects.equals(this.lastUpdatedBy, getBuyerConResContent.lastUpdatedBy) &&
        Objects.equals(this.lastUpdatedByEmail, getBuyerConResContent.lastUpdatedByEmail) &&
        Objects.equals(this.lastUpdatedByFullName, getBuyerConResContent.lastUpdatedByFullName) &&
        Objects.equals(this.lastUpdatedDate, getBuyerConResContent.lastUpdatedDate) &&
        Objects.equals(this.metroCode, getBuyerConResContent.metroCode) &&
        Objects.equals(this.metroDescription, getBuyerConResContent.metroDescription) &&
        Objects.equals(this.name, getBuyerConResContent.name) &&
        Objects.equals(this.namedTag, getBuyerConResContent.namedTag) &&
        Objects.equals(this.notifications, getBuyerConResContent.notifications) &&
        Objects.equals(this.virtualDeviceUUID, getBuyerConResContent.virtualDeviceUUID) &&
        Objects.equals(this._private, getBuyerConResContent._private) &&
        Objects.equals(this.purchaseOrderNumber, getBuyerConResContent.purchaseOrderNumber) &&
        Objects.equals(this.redundancyGroup, getBuyerConResContent.redundancyGroup) &&
        Objects.equals(this.redundancyType, getBuyerConResContent.redundancyType) &&
        Objects.equals(this.redundantUUID, getBuyerConResContent.redundantUUID) &&
        Objects.equals(this.remote, getBuyerConResContent.remote) &&
        Objects.equals(this.self, getBuyerConResContent.self) &&
        Objects.equals(this.sellerMetroCode, getBuyerConResContent.sellerMetroCode) &&
        Objects.equals(this.sellerMetroDescription, getBuyerConResContent.sellerMetroDescription) &&
        Objects.equals(this.sellerOrganizationName, getBuyerConResContent.sellerOrganizationName) &&
        Objects.equals(this.sellerServiceName, getBuyerConResContent.sellerServiceName) &&
        Objects.equals(this.sellerServiceUUID, getBuyerConResContent.sellerServiceUUID) &&
        Objects.equals(this.speed, getBuyerConResContent.speed) &&
        Objects.equals(this.speedUnit, getBuyerConResContent.speedUnit) &&
        Objects.equals(this.providerStatus, getBuyerConResContent.providerStatus) &&
        Objects.equals(this.status, getBuyerConResContent.status) &&
        Objects.equals(this.uuid, getBuyerConResContent.uuid) &&
        Objects.equals(this.vlanSTag, getBuyerConResContent.vlanSTag) &&
        Objects.equals(this.zSidePortName, getBuyerConResContent.zSidePortName) &&
        Objects.equals(this.zSidePortUUID, getBuyerConResContent.zSidePortUUID) &&
        Objects.equals(this.zSideVlanCTag, getBuyerConResContent.zSideVlanCTag) &&
        Objects.equals(this.zSideVlanSTag, getBuyerConResContent.zSideVlanSTag);
  }

  @Override
  public int hashCode() {
    return Objects.hash(asideEncapsulation, authorizationKey, billingTier, buyerOrganizationName, createdBy, createdByEmail, createdByFullName, createdDate, lastUpdatedBy, lastUpdatedByEmail, lastUpdatedByFullName, lastUpdatedDate, metroCode, metroDescription, name, namedTag, notifications, virtualDeviceUUID, _private, purchaseOrderNumber, redundancyGroup, redundancyType, redundantUUID, remote, self, sellerMetroCode, sellerMetroDescription, sellerOrganizationName, sellerServiceName, sellerServiceUUID, speed, speedUnit, providerStatus, status, uuid, vlanSTag, zSidePortName, zSidePortUUID, zSideVlanCTag, zSideVlanSTag);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class GetBuyerConResContent {\n");
    
    sb.append("    asideEncapsulation: ").append(toIndentedString(asideEncapsulation)).append("\n");
    sb.append("    authorizationKey: ").append(toIndentedString(authorizationKey)).append("\n");
    sb.append("    billingTier: ").append(toIndentedString(billingTier)).append("\n");
    sb.append("    buyerOrganizationName: ").append(toIndentedString(buyerOrganizationName)).append("\n");
    sb.append("    createdBy: ").append(toIndentedString(createdBy)).append("\n");
    sb.append("    createdByEmail: ").append(toIndentedString(createdByEmail)).append("\n");
    sb.append("    createdByFullName: ").append(toIndentedString(createdByFullName)).append("\n");
    sb.append("    createdDate: ").append(toIndentedString(createdDate)).append("\n");
    sb.append("    lastUpdatedBy: ").append(toIndentedString(lastUpdatedBy)).append("\n");
    sb.append("    lastUpdatedByEmail: ").append(toIndentedString(lastUpdatedByEmail)).append("\n");
    sb.append("    lastUpdatedByFullName: ").append(toIndentedString(lastUpdatedByFullName)).append("\n");
    sb.append("    lastUpdatedDate: ").append(toIndentedString(lastUpdatedDate)).append("\n");
    sb.append("    metroCode: ").append(toIndentedString(metroCode)).append("\n");
    sb.append("    metroDescription: ").append(toIndentedString(metroDescription)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    namedTag: ").append(toIndentedString(namedTag)).append("\n");
    sb.append("    notifications: ").append(toIndentedString(notifications)).append("\n");
    sb.append("    virtualDeviceUUID: ").append(toIndentedString(virtualDeviceUUID)).append("\n");
    sb.append("    _private: ").append(toIndentedString(_private)).append("\n");
    sb.append("    purchaseOrderNumber: ").append(toIndentedString(purchaseOrderNumber)).append("\n");
    sb.append("    redundancyGroup: ").append(toIndentedString(redundancyGroup)).append("\n");
    sb.append("    redundancyType: ").append(toIndentedString(redundancyType)).append("\n");
    sb.append("    redundantUUID: ").append(toIndentedString(redundantUUID)).append("\n");
    sb.append("    remote: ").append(toIndentedString(remote)).append("\n");
    sb.append("    self: ").append(toIndentedString(self)).append("\n");
    sb.append("    sellerMetroCode: ").append(toIndentedString(sellerMetroCode)).append("\n");
    sb.append("    sellerMetroDescription: ").append(toIndentedString(sellerMetroDescription)).append("\n");
    sb.append("    sellerOrganizationName: ").append(toIndentedString(sellerOrganizationName)).append("\n");
    sb.append("    sellerServiceName: ").append(toIndentedString(sellerServiceName)).append("\n");
    sb.append("    sellerServiceUUID: ").append(toIndentedString(sellerServiceUUID)).append("\n");
    sb.append("    speed: ").append(toIndentedString(speed)).append("\n");
    sb.append("    speedUnit: ").append(toIndentedString(speedUnit)).append("\n");
    sb.append("    providerStatus: ").append(toIndentedString(providerStatus)).append("\n");
    sb.append("    status: ").append(toIndentedString(status)).append("\n");
    sb.append("    uuid: ").append(toIndentedString(uuid)).append("\n");
    sb.append("    vlanSTag: ").append(toIndentedString(vlanSTag)).append("\n");
    sb.append("    zSidePortName: ").append(toIndentedString(zSidePortName)).append("\n");
    sb.append("    zSidePortUUID: ").append(toIndentedString(zSidePortUUID)).append("\n");
    sb.append("    zSideVlanCTag: ").append(toIndentedString(zSideVlanCTag)).append("\n");
    sb.append("    zSideVlanSTag: ").append(toIndentedString(zSideVlanSTag)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

