/*
 * Network Edge APIs
 * API Documentation for NE's Beta APIs. More information about Network Edge marketplace & NE platform can be found [here](https://ecxfabric-documentation.equinix.com/hc/en-us/articles/360021809172-Enterprise-Network-Edge-Beta-Program-Introduction).
 *
 * OpenAPI spec version: General Availability
 * Contact: Network-Edge-Support@equinix.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.equinix.networkedge.model;

import java.util.Objects;

import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModelProperty;

import java.util.ArrayList;
import java.util.List;

/**
 * GETConnectionByUUidResponse
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2019-06-20T13:45:54.773-07:00")
public class GETConnectionByUUidResponse {
  @SerializedName("buyerOrganizationName")
  private String buyerOrganizationName = null;

  @SerializedName("uuid")
  private String uuid = null;

  @SerializedName("name")
  private String name = null;

  @SerializedName("vlanSTag")
  private Integer vlanSTag = null;

  @SerializedName("portUUID")
  private String portUUID = null;

  @SerializedName("portName")
  private String portName = null;

  @SerializedName("asideEncapsulation")
  private String asideEncapsulation = null;

  @SerializedName("metroCode")
  private String metroCode = null;

  @SerializedName("metroDescription")
  private String metroDescription = null;

  @SerializedName("providerStatus")
  private String providerStatus = null;

  @SerializedName("status")
  private String status = null;

  @SerializedName("billingTier")
  private String billingTier = null;

  @SerializedName("authorizationKey")
  private String authorizationKey = null;

  @SerializedName("speed")
  private Integer speed = null;

  @SerializedName("speedUnit")
  private String speedUnit = null;

  @SerializedName("redundancyType")
  private String redundancyType = null;

  @SerializedName("redundancyGroup")
  private String redundancyGroup = null;

  @SerializedName("sellerMetroCode")
  private String sellerMetroCode = null;

  @SerializedName("sellerMetroDescription")
  private String sellerMetroDescription = null;

  @SerializedName("sellerServiceName")
  private String sellerServiceName = null;

  @SerializedName("sellerServiceUUID")
  private String sellerServiceUUID = null;

  @SerializedName("sellerOrganizationName")
  private String sellerOrganizationName = null;

  @SerializedName("notifications")
  private List<String> notifications = null;

  @SerializedName("purchaseOrderNumber")
  private String purchaseOrderNumber = null;

  @SerializedName("namedTag")
  private String namedTag = null;

  @SerializedName("createdDate")
  private String createdDate = null;

  @SerializedName("createdBy")
  private String createdBy = null;

  @SerializedName("createdByFullName")
  private String createdByFullName = null;

  @SerializedName("createdByEmail")
  private String createdByEmail = null;

  @SerializedName("lastUpdatedBy")
  private String lastUpdatedBy = null;

  @SerializedName("lastUpdatedDate")
  private String lastUpdatedDate = null;

  @SerializedName("lastUpdatedByFullName")
  private String lastUpdatedByFullName = null;

  @SerializedName("lastUpdatedByEmail")
  private String lastUpdatedByEmail = null;

  @SerializedName("zSidePortName")
  private String zSidePortName = null;

  @SerializedName("zSidePortUUID")
  private String zSidePortUUID = null;

  @SerializedName("zSideVlanCTag")
  private Integer zSideVlanCTag = null;

  @SerializedName("zSideVlanSTag")
  private Integer zSideVlanSTag = null;

  @SerializedName("remote")
  private Boolean remote = null;

  @SerializedName("private")
  private Boolean _private = null;

  @SerializedName("self")
  private Boolean self = null;

  @SerializedName("redundantUUID")
  private String redundantUUID = null;

  public GETConnectionByUUidResponse buyerOrganizationName(String buyerOrganizationName) {
    this.buyerOrganizationName = buyerOrganizationName;
    return this;
  }

   /**
   * Get buyerOrganizationName
   * @return buyerOrganizationName
  **/
  @ApiModelProperty(example = "Forsythe Solutions Group, Inc.", value = "")
  public String getBuyerOrganizationName() {
    return buyerOrganizationName;
  }

  public void setBuyerOrganizationName(String buyerOrganizationName) {
    this.buyerOrganizationName = buyerOrganizationName;
  }

  public GETConnectionByUUidResponse uuid(String uuid) {
    this.uuid = uuid;
    return this;
  }

   /**
   * Get uuid
   * @return uuid
  **/
  @ApiModelProperty(example = "xxxxx191-xx70-xxxx-xx04-xxxxxxxa37xx", value = "")
  public String getUuid() {
    return uuid;
  }

  public void setUuid(String uuid) {
    this.uuid = uuid;
  }

  public GETConnectionByUUidResponse name(String name) {
    this.name = name;
    return this;
  }

   /**
   * Get name
   * @return name
  **/
  @ApiModelProperty(example = "Test-123", value = "")
  public String getName() {
    return name;
  }

  public void setName(String name) {
    this.name = name;
  }

  public GETConnectionByUUidResponse vlanSTag(Integer vlanSTag) {
    this.vlanSTag = vlanSTag;
    return this;
  }

   /**
   * Get vlanSTag
   * @return vlanSTag
  **/
  @ApiModelProperty(example = "1015", value = "")
  public Integer getVlanSTag() {
    return vlanSTag;
  }

  public void setVlanSTag(Integer vlanSTag) {
    this.vlanSTag = vlanSTag;
  }

  public GETConnectionByUUidResponse portUUID(String portUUID) {
    this.portUUID = portUUID;
    return this;
  }

   /**
   * Get portUUID
   * @return portUUID
  **/
  @ApiModelProperty(example = "xxxxx191-xx70-xxxx-xx04-xxxxxxxa37xx", value = "")
  public String getPortUUID() {
    return portUUID;
  }

  public void setPortUUID(String portUUID) {
    this.portUUID = portUUID;
  }

  public GETConnectionByUUidResponse portName(String portName) {
    this.portName = portName;
    return this;
  }

   /**
   * Get portName
   * @return portName
  **/
  @ApiModelProperty(example = "TEST-CH2-CX-SEC-01", value = "")
  public String getPortName() {
    return portName;
  }

  public void setPortName(String portName) {
    this.portName = portName;
  }

  public GETConnectionByUUidResponse asideEncapsulation(String asideEncapsulation) {
    this.asideEncapsulation = asideEncapsulation;
    return this;
  }

   /**
   * Get asideEncapsulation
   * @return asideEncapsulation
  **/
  @ApiModelProperty(example = "dot1q", value = "")
  public String getAsideEncapsulation() {
    return asideEncapsulation;
  }

  public void setAsideEncapsulation(String asideEncapsulation) {
    this.asideEncapsulation = asideEncapsulation;
  }

  public GETConnectionByUUidResponse metroCode(String metroCode) {
    this.metroCode = metroCode;
    return this;
  }

   /**
   * Get metroCode
   * @return metroCode
  **/
  @ApiModelProperty(example = "CH", value = "")
  public String getMetroCode() {
    return metroCode;
  }

  public void setMetroCode(String metroCode) {
    this.metroCode = metroCode;
  }

  public GETConnectionByUUidResponse metroDescription(String metroDescription) {
    this.metroDescription = metroDescription;
    return this;
  }

   /**
   * Get metroDescription
   * @return metroDescription
  **/
  @ApiModelProperty(example = "Chicago", value = "")
  public String getMetroDescription() {
    return metroDescription;
  }

  public void setMetroDescription(String metroDescription) {
    this.metroDescription = metroDescription;
  }

  public GETConnectionByUUidResponse providerStatus(String providerStatus) {
    this.providerStatus = providerStatus;
    return this;
  }

   /**
   * Get providerStatus
   * @return providerStatus
  **/
  @ApiModelProperty(example = "PROVISIONED", value = "")
  public String getProviderStatus() {
    return providerStatus;
  }

  public void setProviderStatus(String providerStatus) {
    this.providerStatus = providerStatus;
  }

  public GETConnectionByUUidResponse status(String status) {
    this.status = status;
    return this;
  }

   /**
   * Get status
   * @return status
  **/
  @ApiModelProperty(example = "PROVISIONED", value = "")
  public String getStatus() {
    return status;
  }

  public void setStatus(String status) {
    this.status = status;
  }

  public GETConnectionByUUidResponse billingTier(String billingTier) {
    this.billingTier = billingTier;
    return this;
  }

   /**
   * Get billingTier
   * @return billingTier
  **/
  @ApiModelProperty(example = "Up to 500MB", value = "")
  public String getBillingTier() {
    return billingTier;
  }

  public void setBillingTier(String billingTier) {
    this.billingTier = billingTier;
  }

  public GETConnectionByUUidResponse authorizationKey(String authorizationKey) {
    this.authorizationKey = authorizationKey;
    return this;
  }

   /**
   * Get authorizationKey
   * @return authorizationKey
  **/
  @ApiModelProperty(example = "xxxxx191-xx70-xxxx-xx04-xxxxxxxa37xx", value = "")
  public String getAuthorizationKey() {
    return authorizationKey;
  }

  public void setAuthorizationKey(String authorizationKey) {
    this.authorizationKey = authorizationKey;
  }

  public GETConnectionByUUidResponse speed(Integer speed) {
    this.speed = speed;
    return this;
  }

   /**
   * Get speed
   * @return speed
  **/
  @ApiModelProperty(example = "500", value = "")
  public Integer getSpeed() {
    return speed;
  }

  public void setSpeed(Integer speed) {
    this.speed = speed;
  }

  public GETConnectionByUUidResponse speedUnit(String speedUnit) {
    this.speedUnit = speedUnit;
    return this;
  }

   /**
   * Get speedUnit
   * @return speedUnit
  **/
  @ApiModelProperty(example = "MB", value = "")
  public String getSpeedUnit() {
    return speedUnit;
  }

  public void setSpeedUnit(String speedUnit) {
    this.speedUnit = speedUnit;
  }

  public GETConnectionByUUidResponse redundancyType(String redundancyType) {
    this.redundancyType = redundancyType;
    return this;
  }

   /**
   * Get redundancyType
   * @return redundancyType
  **/
  @ApiModelProperty(example = "secondary", value = "")
  public String getRedundancyType() {
    return redundancyType;
  }

  public void setRedundancyType(String redundancyType) {
    this.redundancyType = redundancyType;
  }

  public GETConnectionByUUidResponse redundancyGroup(String redundancyGroup) {
    this.redundancyGroup = redundancyGroup;
    return this;
  }

   /**
   * Get redundancyGroup
   * @return redundancyGroup
  **/
  @ApiModelProperty(example = "xxxxx191-xx70-xxxx-xx04-xxxxxxxa37xx", value = "")
  public String getRedundancyGroup() {
    return redundancyGroup;
  }

  public void setRedundancyGroup(String redundancyGroup) {
    this.redundancyGroup = redundancyGroup;
  }

  public GETConnectionByUUidResponse sellerMetroCode(String sellerMetroCode) {
    this.sellerMetroCode = sellerMetroCode;
    return this;
  }

   /**
   * Get sellerMetroCode
   * @return sellerMetroCode
  **/
  @ApiModelProperty(example = "CH", value = "")
  public String getSellerMetroCode() {
    return sellerMetroCode;
  }

  public void setSellerMetroCode(String sellerMetroCode) {
    this.sellerMetroCode = sellerMetroCode;
  }

  public GETConnectionByUUidResponse sellerMetroDescription(String sellerMetroDescription) {
    this.sellerMetroDescription = sellerMetroDescription;
    return this;
  }

   /**
   * Get sellerMetroDescription
   * @return sellerMetroDescription
  **/
  @ApiModelProperty(example = "Chicago", value = "")
  public String getSellerMetroDescription() {
    return sellerMetroDescription;
  }

  public void setSellerMetroDescription(String sellerMetroDescription) {
    this.sellerMetroDescription = sellerMetroDescription;
  }

  public GETConnectionByUUidResponse sellerServiceName(String sellerServiceName) {
    this.sellerServiceName = sellerServiceName;
    return this;
  }

   /**
   * Get sellerServiceName
   * @return sellerServiceName
  **/
  @ApiModelProperty(example = "XYZ Cloud Service", value = "")
  public String getSellerServiceName() {
    return sellerServiceName;
  }

  public void setSellerServiceName(String sellerServiceName) {
    this.sellerServiceName = sellerServiceName;
  }

  public GETConnectionByUUidResponse sellerServiceUUID(String sellerServiceUUID) {
    this.sellerServiceUUID = sellerServiceUUID;
    return this;
  }

   /**
   * Get sellerServiceUUID
   * @return sellerServiceUUID
  **/
  @ApiModelProperty(example = "xxxxx191-xx70-xxxx-xx04-xxxxxxxa37xx", value = "")
  public String getSellerServiceUUID() {
    return sellerServiceUUID;
  }

  public void setSellerServiceUUID(String sellerServiceUUID) {
    this.sellerServiceUUID = sellerServiceUUID;
  }

  public GETConnectionByUUidResponse sellerOrganizationName(String sellerOrganizationName) {
    this.sellerOrganizationName = sellerOrganizationName;
    return this;
  }

   /**
   * Get sellerOrganizationName
   * @return sellerOrganizationName
  **/
  @ApiModelProperty(example = "EQUINIX-CLOUD-EXCHANGE", value = "")
  public String getSellerOrganizationName() {
    return sellerOrganizationName;
  }

  public void setSellerOrganizationName(String sellerOrganizationName) {
    this.sellerOrganizationName = sellerOrganizationName;
  }

  public GETConnectionByUUidResponse notifications(List<String> notifications) {
    this.notifications = notifications;
    return this;
  }

  public GETConnectionByUUidResponse addNotificationsItem(String notificationsItem) {
    if (this.notifications == null) {
      this.notifications = new ArrayList<String>();
    }
    this.notifications.add(notificationsItem);
    return this;
  }

   /**
   * Get notifications
   * @return notifications
  **/
  @ApiModelProperty(value = "")
  public List<String> getNotifications() {
    return notifications;
  }

  public void setNotifications(List<String> notifications) {
    this.notifications = notifications;
  }

  public GETConnectionByUUidResponse purchaseOrderNumber(String purchaseOrderNumber) {
    this.purchaseOrderNumber = purchaseOrderNumber;
    return this;
  }

   /**
   * Get purchaseOrderNumber
   * @return purchaseOrderNumber
  **/
  @ApiModelProperty(example = "O-1234567890", value = "")
  public String getPurchaseOrderNumber() {
    return purchaseOrderNumber;
  }

  public void setPurchaseOrderNumber(String purchaseOrderNumber) {
    this.purchaseOrderNumber = purchaseOrderNumber;
  }

  public GETConnectionByUUidResponse namedTag(String namedTag) {
    this.namedTag = namedTag;
    return this;
  }

   /**
   * Get namedTag
   * @return namedTag
  **/
  @ApiModelProperty(example = "Private", value = "")
  public String getNamedTag() {
    return namedTag;
  }

  public void setNamedTag(String namedTag) {
    this.namedTag = namedTag;
  }

  public GETConnectionByUUidResponse createdDate(String createdDate) {
    this.createdDate = createdDate;
    return this;
  }

   /**
   * Get createdDate
   * @return createdDate
  **/
  @ApiModelProperty(example = "2017-09-26T22:46:24.312Z", value = "")
  public String getCreatedDate() {
    return createdDate;
  }

  public void setCreatedDate(String createdDate) {
    this.createdDate = createdDate;
  }

  public GETConnectionByUUidResponse createdBy(String createdBy) {
    this.createdBy = createdBy;
    return this;
  }

   /**
   * Get createdBy
   * @return createdBy
  **/
  @ApiModelProperty(example = "sandboxuser@example-company.com", value = "")
  public String getCreatedBy() {
    return createdBy;
  }

  public void setCreatedBy(String createdBy) {
    this.createdBy = createdBy;
  }

  public GETConnectionByUUidResponse createdByFullName(String createdByFullName) {
    this.createdByFullName = createdByFullName;
    return this;
  }

   /**
   * Get createdByFullName
   * @return createdByFullName
  **/
  @ApiModelProperty(example = "Sandbox User", value = "")
  public String getCreatedByFullName() {
    return createdByFullName;
  }

  public void setCreatedByFullName(String createdByFullName) {
    this.createdByFullName = createdByFullName;
  }

  public GETConnectionByUUidResponse createdByEmail(String createdByEmail) {
    this.createdByEmail = createdByEmail;
    return this;
  }

   /**
   * Get createdByEmail
   * @return createdByEmail
  **/
  @ApiModelProperty(example = "sandboxuser@example-company.com", value = "")
  public String getCreatedByEmail() {
    return createdByEmail;
  }

  public void setCreatedByEmail(String createdByEmail) {
    this.createdByEmail = createdByEmail;
  }

  public GETConnectionByUUidResponse lastUpdatedBy(String lastUpdatedBy) {
    this.lastUpdatedBy = lastUpdatedBy;
    return this;
  }

   /**
   * Get lastUpdatedBy
   * @return lastUpdatedBy
  **/
  @ApiModelProperty(example = "sandboxuser@example-company.com", value = "")
  public String getLastUpdatedBy() {
    return lastUpdatedBy;
  }

  public void setLastUpdatedBy(String lastUpdatedBy) {
    this.lastUpdatedBy = lastUpdatedBy;
  }

  public GETConnectionByUUidResponse lastUpdatedDate(String lastUpdatedDate) {
    this.lastUpdatedDate = lastUpdatedDate;
    return this;
  }

   /**
   * Get lastUpdatedDate
   * @return lastUpdatedDate
  **/
  @ApiModelProperty(example = "2017-09-26T23:01:46Z", value = "")
  public String getLastUpdatedDate() {
    return lastUpdatedDate;
  }

  public void setLastUpdatedDate(String lastUpdatedDate) {
    this.lastUpdatedDate = lastUpdatedDate;
  }

  public GETConnectionByUUidResponse lastUpdatedByFullName(String lastUpdatedByFullName) {
    this.lastUpdatedByFullName = lastUpdatedByFullName;
    return this;
  }

   /**
   * Get lastUpdatedByFullName
   * @return lastUpdatedByFullName
  **/
  @ApiModelProperty(example = "Sandbox User", value = "")
  public String getLastUpdatedByFullName() {
    return lastUpdatedByFullName;
  }

  public void setLastUpdatedByFullName(String lastUpdatedByFullName) {
    this.lastUpdatedByFullName = lastUpdatedByFullName;
  }

  public GETConnectionByUUidResponse lastUpdatedByEmail(String lastUpdatedByEmail) {
    this.lastUpdatedByEmail = lastUpdatedByEmail;
    return this;
  }

   /**
   * Get lastUpdatedByEmail
   * @return lastUpdatedByEmail
  **/
  @ApiModelProperty(example = "sandboxuser@example-company.com", value = "")
  public String getLastUpdatedByEmail() {
    return lastUpdatedByEmail;
  }

  public void setLastUpdatedByEmail(String lastUpdatedByEmail) {
    this.lastUpdatedByEmail = lastUpdatedByEmail;
  }

  public GETConnectionByUUidResponse zSidePortName(String zSidePortName) {
    this.zSidePortName = zSidePortName;
    return this;
  }

   /**
   * Get zSidePortName
   * @return zSidePortName
  **/
  @ApiModelProperty(example = "TEST-CHG-06GMR-Tes-2-TES-C", value = "")
  public String getZSidePortName() {
    return zSidePortName;
  }

  public void setZSidePortName(String zSidePortName) {
    this.zSidePortName = zSidePortName;
  }

  public GETConnectionByUUidResponse zSidePortUUID(String zSidePortUUID) {
    this.zSidePortUUID = zSidePortUUID;
    return this;
  }

   /**
   * Get zSidePortUUID
   * @return zSidePortUUID
  **/
  @ApiModelProperty(example = "xxxxx191-xx70-xxxx-xx04-xxxxxxxa37xx", value = "")
  public String getZSidePortUUID() {
    return zSidePortUUID;
  }

  public void setZSidePortUUID(String zSidePortUUID) {
    this.zSidePortUUID = zSidePortUUID;
  }

  public GETConnectionByUUidResponse zSideVlanCTag(Integer zSideVlanCTag) {
    this.zSideVlanCTag = zSideVlanCTag;
    return this;
  }

   /**
   * Get zSideVlanCTag
   * @return zSideVlanCTag
  **/
  @ApiModelProperty(example = "515", value = "")
  public Integer getZSideVlanCTag() {
    return zSideVlanCTag;
  }

  public void setZSideVlanCTag(Integer zSideVlanCTag) {
    this.zSideVlanCTag = zSideVlanCTag;
  }

  public GETConnectionByUUidResponse zSideVlanSTag(Integer zSideVlanSTag) {
    this.zSideVlanSTag = zSideVlanSTag;
    return this;
  }

   /**
   * Get zSideVlanSTag
   * @return zSideVlanSTag
  **/
  @ApiModelProperty(example = "2", value = "")
  public Integer getZSideVlanSTag() {
    return zSideVlanSTag;
  }

  public void setZSideVlanSTag(Integer zSideVlanSTag) {
    this.zSideVlanSTag = zSideVlanSTag;
  }

  public GETConnectionByUUidResponse remote(Boolean remote) {
    this.remote = remote;
    return this;
  }

   /**
   * Get remote
   * @return remote
  **/
  @ApiModelProperty(example = "false", value = "")
  public Boolean isRemote() {
    return remote;
  }

  public void setRemote(Boolean remote) {
    this.remote = remote;
  }

  public GETConnectionByUUidResponse _private(Boolean _private) {
    this._private = _private;
    return this;
  }

   /**
   * Get _private
   * @return _private
  **/
  @ApiModelProperty(example = "false", value = "")
  public Boolean isPrivate() {
    return _private;
  }

  public void setPrivate(Boolean _private) {
    this._private = _private;
  }

  public GETConnectionByUUidResponse self(Boolean self) {
    this.self = self;
    return this;
  }

   /**
   * Get self
   * @return self
  **/
  @ApiModelProperty(example = "false", value = "")
  public Boolean isSelf() {
    return self;
  }

  public void setSelf(Boolean self) {
    this.self = self;
  }

  public GETConnectionByUUidResponse redundantUUID(String redundantUUID) {
    this.redundantUUID = redundantUUID;
    return this;
  }

   /**
   * Get redundantUUID
   * @return redundantUUID
  **/
  @ApiModelProperty(example = "xxxxx191-xx70-xxxx-xx04-xxxxxxxa37xx", value = "")
  public String getRedundantUUID() {
    return redundantUUID;
  }

  public void setRedundantUUID(String redundantUUID) {
    this.redundantUUID = redundantUUID;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    GETConnectionByUUidResponse geTConnectionByUUidResponse = (GETConnectionByUUidResponse) o;
    return Objects.equals(this.buyerOrganizationName, geTConnectionByUUidResponse.buyerOrganizationName) &&
        Objects.equals(this.uuid, geTConnectionByUUidResponse.uuid) &&
        Objects.equals(this.name, geTConnectionByUUidResponse.name) &&
        Objects.equals(this.vlanSTag, geTConnectionByUUidResponse.vlanSTag) &&
        Objects.equals(this.portUUID, geTConnectionByUUidResponse.portUUID) &&
        Objects.equals(this.portName, geTConnectionByUUidResponse.portName) &&
        Objects.equals(this.asideEncapsulation, geTConnectionByUUidResponse.asideEncapsulation) &&
        Objects.equals(this.metroCode, geTConnectionByUUidResponse.metroCode) &&
        Objects.equals(this.metroDescription, geTConnectionByUUidResponse.metroDescription) &&
        Objects.equals(this.providerStatus, geTConnectionByUUidResponse.providerStatus) &&
        Objects.equals(this.status, geTConnectionByUUidResponse.status) &&
        Objects.equals(this.billingTier, geTConnectionByUUidResponse.billingTier) &&
        Objects.equals(this.authorizationKey, geTConnectionByUUidResponse.authorizationKey) &&
        Objects.equals(this.speed, geTConnectionByUUidResponse.speed) &&
        Objects.equals(this.speedUnit, geTConnectionByUUidResponse.speedUnit) &&
        Objects.equals(this.redundancyType, geTConnectionByUUidResponse.redundancyType) &&
        Objects.equals(this.redundancyGroup, geTConnectionByUUidResponse.redundancyGroup) &&
        Objects.equals(this.sellerMetroCode, geTConnectionByUUidResponse.sellerMetroCode) &&
        Objects.equals(this.sellerMetroDescription, geTConnectionByUUidResponse.sellerMetroDescription) &&
        Objects.equals(this.sellerServiceName, geTConnectionByUUidResponse.sellerServiceName) &&
        Objects.equals(this.sellerServiceUUID, geTConnectionByUUidResponse.sellerServiceUUID) &&
        Objects.equals(this.sellerOrganizationName, geTConnectionByUUidResponse.sellerOrganizationName) &&
        Objects.equals(this.notifications, geTConnectionByUUidResponse.notifications) &&
        Objects.equals(this.purchaseOrderNumber, geTConnectionByUUidResponse.purchaseOrderNumber) &&
        Objects.equals(this.namedTag, geTConnectionByUUidResponse.namedTag) &&
        Objects.equals(this.createdDate, geTConnectionByUUidResponse.createdDate) &&
        Objects.equals(this.createdBy, geTConnectionByUUidResponse.createdBy) &&
        Objects.equals(this.createdByFullName, geTConnectionByUUidResponse.createdByFullName) &&
        Objects.equals(this.createdByEmail, geTConnectionByUUidResponse.createdByEmail) &&
        Objects.equals(this.lastUpdatedBy, geTConnectionByUUidResponse.lastUpdatedBy) &&
        Objects.equals(this.lastUpdatedDate, geTConnectionByUUidResponse.lastUpdatedDate) &&
        Objects.equals(this.lastUpdatedByFullName, geTConnectionByUUidResponse.lastUpdatedByFullName) &&
        Objects.equals(this.lastUpdatedByEmail, geTConnectionByUUidResponse.lastUpdatedByEmail) &&
        Objects.equals(this.zSidePortName, geTConnectionByUUidResponse.zSidePortName) &&
        Objects.equals(this.zSidePortUUID, geTConnectionByUUidResponse.zSidePortUUID) &&
        Objects.equals(this.zSideVlanCTag, geTConnectionByUUidResponse.zSideVlanCTag) &&
        Objects.equals(this.zSideVlanSTag, geTConnectionByUUidResponse.zSideVlanSTag) &&
        Objects.equals(this.remote, geTConnectionByUUidResponse.remote) &&
        Objects.equals(this._private, geTConnectionByUUidResponse._private) &&
        Objects.equals(this.self, geTConnectionByUUidResponse.self) &&
        Objects.equals(this.redundantUUID, geTConnectionByUUidResponse.redundantUUID);
  }

  @Override
  public int hashCode() {
    return Objects.hash(buyerOrganizationName, uuid, name, vlanSTag, portUUID, portName, asideEncapsulation, metroCode, metroDescription, providerStatus, status, billingTier, authorizationKey, speed, speedUnit, redundancyType, redundancyGroup, sellerMetroCode, sellerMetroDescription, sellerServiceName, sellerServiceUUID, sellerOrganizationName, notifications, purchaseOrderNumber, namedTag, createdDate, createdBy, createdByFullName, createdByEmail, lastUpdatedBy, lastUpdatedDate, lastUpdatedByFullName, lastUpdatedByEmail, zSidePortName, zSidePortUUID, zSideVlanCTag, zSideVlanSTag, remote, _private, self, redundantUUID);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class GETConnectionByUUidResponse {\n");
    
    sb.append("    buyerOrganizationName: ").append(toIndentedString(buyerOrganizationName)).append("\n");
    sb.append("    uuid: ").append(toIndentedString(uuid)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    vlanSTag: ").append(toIndentedString(vlanSTag)).append("\n");
    sb.append("    portUUID: ").append(toIndentedString(portUUID)).append("\n");
    sb.append("    portName: ").append(toIndentedString(portName)).append("\n");
    sb.append("    asideEncapsulation: ").append(toIndentedString(asideEncapsulation)).append("\n");
    sb.append("    metroCode: ").append(toIndentedString(metroCode)).append("\n");
    sb.append("    metroDescription: ").append(toIndentedString(metroDescription)).append("\n");
    sb.append("    providerStatus: ").append(toIndentedString(providerStatus)).append("\n");
    sb.append("    status: ").append(toIndentedString(status)).append("\n");
    sb.append("    billingTier: ").append(toIndentedString(billingTier)).append("\n");
    sb.append("    authorizationKey: ").append(toIndentedString(authorizationKey)).append("\n");
    sb.append("    speed: ").append(toIndentedString(speed)).append("\n");
    sb.append("    speedUnit: ").append(toIndentedString(speedUnit)).append("\n");
    sb.append("    redundancyType: ").append(toIndentedString(redundancyType)).append("\n");
    sb.append("    redundancyGroup: ").append(toIndentedString(redundancyGroup)).append("\n");
    sb.append("    sellerMetroCode: ").append(toIndentedString(sellerMetroCode)).append("\n");
    sb.append("    sellerMetroDescription: ").append(toIndentedString(sellerMetroDescription)).append("\n");
    sb.append("    sellerServiceName: ").append(toIndentedString(sellerServiceName)).append("\n");
    sb.append("    sellerServiceUUID: ").append(toIndentedString(sellerServiceUUID)).append("\n");
    sb.append("    sellerOrganizationName: ").append(toIndentedString(sellerOrganizationName)).append("\n");
    sb.append("    notifications: ").append(toIndentedString(notifications)).append("\n");
    sb.append("    purchaseOrderNumber: ").append(toIndentedString(purchaseOrderNumber)).append("\n");
    sb.append("    namedTag: ").append(toIndentedString(namedTag)).append("\n");
    sb.append("    createdDate: ").append(toIndentedString(createdDate)).append("\n");
    sb.append("    createdBy: ").append(toIndentedString(createdBy)).append("\n");
    sb.append("    createdByFullName: ").append(toIndentedString(createdByFullName)).append("\n");
    sb.append("    createdByEmail: ").append(toIndentedString(createdByEmail)).append("\n");
    sb.append("    lastUpdatedBy: ").append(toIndentedString(lastUpdatedBy)).append("\n");
    sb.append("    lastUpdatedDate: ").append(toIndentedString(lastUpdatedDate)).append("\n");
    sb.append("    lastUpdatedByFullName: ").append(toIndentedString(lastUpdatedByFullName)).append("\n");
    sb.append("    lastUpdatedByEmail: ").append(toIndentedString(lastUpdatedByEmail)).append("\n");
    sb.append("    zSidePortName: ").append(toIndentedString(zSidePortName)).append("\n");
    sb.append("    zSidePortUUID: ").append(toIndentedString(zSidePortUUID)).append("\n");
    sb.append("    zSideVlanCTag: ").append(toIndentedString(zSideVlanCTag)).append("\n");
    sb.append("    zSideVlanSTag: ").append(toIndentedString(zSideVlanSTag)).append("\n");
    sb.append("    remote: ").append(toIndentedString(remote)).append("\n");
    sb.append("    _private: ").append(toIndentedString(_private)).append("\n");
    sb.append("    self: ").append(toIndentedString(self)).append("\n");
    sb.append("    redundantUUID: ").append(toIndentedString(redundantUUID)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

