/*
 * Network Edge APIs
 * API Documentation for NE's Beta APIs. More information about Network Edge marketplace & NE platform can be found [here](https://ecxfabric-documentation.equinix.com/hc/en-us/articles/360021809172-Enterprise-Network-Edge-Beta-Program-Introduction).
 *
 * OpenAPI spec version: General Availability
 * Contact: Network-Edge-Support@equinix.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.equinix.networkedge.model;

import java.util.Objects;

import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModelProperty;

/**
 * GetServProfServicesRespContentfeatures
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2019-06-20T13:45:54.773-07:00")
public class GetServProfServicesRespContentfeatures {
  @SerializedName("cloudReach")
  private Boolean cloudReach = null;

  @SerializedName("testProfile")
  private Boolean testProfile = null;

  public GetServProfServicesRespContentfeatures cloudReach(Boolean cloudReach) {
    this.cloudReach = cloudReach;
    return this;
  }

   /**
   * Get cloudReach
   * @return cloudReach
  **/
  @ApiModelProperty(example = "true", value = "")
  public Boolean isCloudReach() {
    return cloudReach;
  }

  public void setCloudReach(Boolean cloudReach) {
    this.cloudReach = cloudReach;
  }

  public GetServProfServicesRespContentfeatures testProfile(Boolean testProfile) {
    this.testProfile = testProfile;
    return this;
  }

   /**
   * Get testProfile
   * @return testProfile
  **/
  @ApiModelProperty(example = "false", value = "")
  public Boolean isTestProfile() {
    return testProfile;
  }

  public void setTestProfile(Boolean testProfile) {
    this.testProfile = testProfile;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    GetServProfServicesRespContentfeatures getServProfServicesRespContentfeatures = (GetServProfServicesRespContentfeatures) o;
    return Objects.equals(this.cloudReach, getServProfServicesRespContentfeatures.cloudReach) &&
        Objects.equals(this.testProfile, getServProfServicesRespContentfeatures.testProfile);
  }

  @Override
  public int hashCode() {
    return Objects.hash(cloudReach, testProfile);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class GetServProfServicesRespContentfeatures {\n");
    
    sb.append("    cloudReach: ").append(toIndentedString(cloudReach)).append("\n");
    sb.append("    testProfile: ").append(toIndentedString(testProfile)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

