/*
 * Network Edge APIs
 * API Documentation for NE's Beta APIs. More information about Network Edge marketplace & NE platform can be found [here](https://ecxfabric-documentation.equinix.com/hc/en-us/articles/360021809172-Enterprise-Network-Edge-Beta-Program-Introduction).
 *
 * OpenAPI spec version: General Availability
 * Contact: Network-Edge-Support@equinix.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.equinix.networkedge.model;

import java.util.Objects;

import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModelProperty;

/**
 * MetroAccountResponse
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2019-06-20T13:45:54.773-07:00")
public class MetroAccountResponse {
  @SerializedName("accountName")
  private String accountName = null;

  @SerializedName("accountNumber")
  private Integer accountNumber = null;

  @SerializedName("accountUcmId")
  private String accountUcmId = null;

  @SerializedName("accountStatus")
  private String accountStatus = null;

  @SerializedName("referenceId")
  private String referenceId = null;

  public MetroAccountResponse accountName(String accountName) {
    this.accountName = accountName;
    return this;
  }

   /**
   * account Name
   * @return accountName
  **/
  @ApiModelProperty(example = "nfv1", value = "account Name")
  public String getAccountName() {
    return accountName;
  }

  public void setAccountName(String accountName) {
    this.accountName = accountName;
  }

  public MetroAccountResponse accountNumber(Integer accountNumber) {
    this.accountNumber = accountNumber;
    return this;
  }

   /**
   * account number
   * @return accountNumber
  **/
  @ApiModelProperty(example = "2252619", value = "account number")
  public Integer getAccountNumber() {
    return accountNumber;
  }

  public void setAccountNumber(Integer accountNumber) {
    this.accountNumber = accountNumber;
  }

  public MetroAccountResponse accountUcmId(String accountUcmId) {
    this.accountUcmId = accountUcmId;
    return this;
  }

   /**
   * account UcmId
   * @return accountUcmId
  **/
  @ApiModelProperty(example = "92D27009-EA33-4b60-B4FB-D3C4ED589649", value = "account UcmId")
  public String getAccountUcmId() {
    return accountUcmId;
  }

  public void setAccountUcmId(String accountUcmId) {
    this.accountUcmId = accountUcmId;
  }

  public MetroAccountResponse accountStatus(String accountStatus) {
    this.accountStatus = accountStatus;
    return this;
  }

   /**
   * account status
   * @return accountStatus
  **/
  @ApiModelProperty(example = "Active", value = "account status")
  public String getAccountStatus() {
    return accountStatus;
  }

  public void setAccountStatus(String accountStatus) {
    this.accountStatus = accountStatus;
  }

  public MetroAccountResponse referenceId(String referenceId) {
    this.referenceId = referenceId;
    return this;
  }

   /**
   * referenceId
   * @return referenceId
  **/
  @ApiModelProperty(example = "", value = "referenceId")
  public String getReferenceId() {
    return referenceId;
  }

  public void setReferenceId(String referenceId) {
    this.referenceId = referenceId;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    MetroAccountResponse metroAccountResponse = (MetroAccountResponse) o;
    return Objects.equals(this.accountName, metroAccountResponse.accountName) &&
        Objects.equals(this.accountNumber, metroAccountResponse.accountNumber) &&
        Objects.equals(this.accountUcmId, metroAccountResponse.accountUcmId) &&
        Objects.equals(this.accountStatus, metroAccountResponse.accountStatus) &&
        Objects.equals(this.referenceId, metroAccountResponse.referenceId);
  }

  @Override
  public int hashCode() {
    return Objects.hash(accountName, accountNumber, accountUcmId, accountStatus, referenceId);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class MetroAccountResponse {\n");
    
    sb.append("    accountName: ").append(toIndentedString(accountName)).append("\n");
    sb.append("    accountNumber: ").append(toIndentedString(accountNumber)).append("\n");
    sb.append("    accountUcmId: ").append(toIndentedString(accountUcmId)).append("\n");
    sb.append("    accountStatus: ").append(toIndentedString(accountStatus)).append("\n");
    sb.append("    referenceId: ").append(toIndentedString(referenceId)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

