/*
 * Network Edge APIs
 * API Documentation for NE's Beta APIs. More information about Network Edge marketplace & NE platform can be found [here](https://ecxfabric-documentation.equinix.com/hc/en-us/articles/360021809172-Enterprise-Network-Edge-Beta-Program-Introduction).
 *
 * OpenAPI spec version: General Availability
 * Contact: Network-Edge-Support@equinix.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.equinix.networkedge.model;

import java.util.Objects;

import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModelProperty;

/**
 * OAuthResponse
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2019-06-20T13:45:54.773-07:00")
public class OAuthResponse {
  @SerializedName("access_token")
  private String accessToken = null;

  @SerializedName("token_timeout")
  private Integer tokenTimeout = null;

  @SerializedName("user_name")
  private String userName = null;

  @SerializedName("token_type")
  private String tokenType = null;

  @SerializedName("refresh_token")
  private String refreshToken = null;

  @SerializedName("refresh_token_timeout")
  private String refreshTokenTimeout = null;

  public OAuthResponse accessToken(String accessToken) {
    this.accessToken = accessToken;
    return this;
  }

   /**
   * Get accessToken
   * @return accessToken
  **/
  @ApiModelProperty(example = "xxxxBxxitwxxxxx8xxRxxxxxR2xx", value = "")
  public String getAccessToken() {
    return accessToken;
  }

  public void setAccessToken(String accessToken) {
    this.accessToken = accessToken;
  }

  public OAuthResponse tokenTimeout(Integer tokenTimeout) {
    this.tokenTimeout = tokenTimeout;
    return this;
  }

   /**
   * Get tokenTimeout
   * @return tokenTimeout
  **/
  @ApiModelProperty(example = "3599", value = "")
  public Integer getTokenTimeout() {
    return tokenTimeout;
  }

  public void setTokenTimeout(Integer tokenTimeout) {
    this.tokenTimeout = tokenTimeout;
  }

  public OAuthResponse userName(String userName) {
    this.userName = userName;
    return this;
  }

   /**
   * Get userName
   * @return userName
  **/
  @ApiModelProperty(example = "sandboxuser@example-company.com", value = "")
  public String getUserName() {
    return userName;
  }

  public void setUserName(String userName) {
    this.userName = userName;
  }

  public OAuthResponse tokenType(String tokenType) {
    this.tokenType = tokenType;
    return this;
  }

   /**
   * Get tokenType
   * @return tokenType
  **/
  @ApiModelProperty(example = "Bearer", value = "")
  public String getTokenType() {
    return tokenType;
  }

  public void setTokenType(String tokenType) {
    this.tokenType = tokenType;
  }

  public OAuthResponse refreshToken(String refreshToken) {
    this.refreshToken = refreshToken;
    return this;
  }

   /**
   * Get refreshToken
   * @return refreshToken
  **/
  @ApiModelProperty(example = "xxxxQbGUnxxxxHsyxxxxxxxBBxxxxYxxxxxxxf4xxx", value = "")
  public String getRefreshToken() {
    return refreshToken;
  }

  public void setRefreshToken(String refreshToken) {
    this.refreshToken = refreshToken;
  }

  public OAuthResponse refreshTokenTimeout(String refreshTokenTimeout) {
    this.refreshTokenTimeout = refreshTokenTimeout;
    return this;
  }

   /**
   * Get refreshTokenTimeout
   * @return refreshTokenTimeout
  **/
  @ApiModelProperty(example = "5182560", value = "")
  public String getRefreshTokenTimeout() {
    return refreshTokenTimeout;
  }

  public void setRefreshTokenTimeout(String refreshTokenTimeout) {
    this.refreshTokenTimeout = refreshTokenTimeout;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    OAuthResponse oauthResponse = (OAuthResponse) o;
    return Objects.equals(this.accessToken, oauthResponse.accessToken) &&
        Objects.equals(this.tokenTimeout, oauthResponse.tokenTimeout) &&
        Objects.equals(this.userName, oauthResponse.userName) &&
        Objects.equals(this.tokenType, oauthResponse.tokenType) &&
        Objects.equals(this.refreshToken, oauthResponse.refreshToken) &&
        Objects.equals(this.refreshTokenTimeout, oauthResponse.refreshTokenTimeout);
  }

  @Override
  public int hashCode() {
    return Objects.hash(accessToken, tokenTimeout, userName, tokenType, refreshToken, refreshTokenTimeout);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class OAuthResponse {\n");
    
    sb.append("    accessToken: ").append(toIndentedString(accessToken)).append("\n");
    sb.append("    tokenTimeout: ").append(toIndentedString(tokenTimeout)).append("\n");
    sb.append("    userName: ").append(toIndentedString(userName)).append("\n");
    sb.append("    tokenType: ").append(toIndentedString(tokenType)).append("\n");
    sb.append("    refreshToken: ").append(toIndentedString(refreshToken)).append("\n");
    sb.append("    refreshTokenTimeout: ").append(toIndentedString(refreshTokenTimeout)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

