/*
 * Network Edge APIs
 * API Documentation for NE's Beta APIs. More information about Network Edge marketplace & NE platform can be found [here](https://ecxfabric-documentation.equinix.com/hc/en-us/articles/360021809172-Enterprise-Network-Edge-Beta-Program-Introduction).
 *
 * OpenAPI spec version: General Availability
 * Contact: Network-Edge-Support@equinix.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.equinix.networkedge.model;

import java.util.Objects;

import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModelProperty;

/**
 * OAuthErrorResponse
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2019-06-20T13:45:54.773-07:00")
public class OAuthErrorResponse {
  @SerializedName("errorDomain")
  private String errorDomain = null;

  @SerializedName("errorTitle")
  private String errorTitle = null;

  @SerializedName("errorCode")
  private String errorCode = null;

  @SerializedName("developerMessage")
  private String developerMessage = null;

  @SerializedName("errorMessage")
  private String errorMessage = null;

  public OAuthErrorResponse errorDomain(String errorDomain) {
    this.errorDomain = errorDomain;
    return this;
  }

   /**
   * Get errorDomain
   * @return errorDomain
  **/
  @ApiModelProperty(example = "apps-fqa", value = "")
  public String getErrorDomain() {
    return errorDomain;
  }

  public void setErrorDomain(String errorDomain) {
    this.errorDomain = errorDomain;
  }

  public OAuthErrorResponse errorTitle(String errorTitle) {
    this.errorTitle = errorTitle;
    return this;
  }

   /**
   * Get errorTitle
   * @return errorTitle
  **/
  @ApiModelProperty(example = "Invalid Username/Password", value = "")
  public String getErrorTitle() {
    return errorTitle;
  }

  public void setErrorTitle(String errorTitle) {
    this.errorTitle = errorTitle;
  }

  public OAuthErrorResponse errorCode(String errorCode) {
    this.errorCode = errorCode;
    return this;
  }

   /**
   * Get errorCode
   * @return errorCode
  **/
  @ApiModelProperty(example = "S1003", value = "")
  public String getErrorCode() {
    return errorCode;
  }

  public void setErrorCode(String errorCode) {
    this.errorCode = errorCode;
  }

  public OAuthErrorResponse developerMessage(String developerMessage) {
    this.developerMessage = developerMessage;
    return this;
  }

   /**
   * Get developerMessage
   * @return developerMessage
  **/
  @ApiModelProperty(example = "Invalid Username/Password", value = "")
  public String getDeveloperMessage() {
    return developerMessage;
  }

  public void setDeveloperMessage(String developerMessage) {
    this.developerMessage = developerMessage;
  }

  public OAuthErrorResponse errorMessage(String errorMessage) {
    this.errorMessage = errorMessage;
    return this;
  }

   /**
   * Get errorMessage
   * @return errorMessage
  **/
  @ApiModelProperty(example = "Username or password wasn't recognized, please try again.", value = "")
  public String getErrorMessage() {
    return errorMessage;
  }

  public void setErrorMessage(String errorMessage) {
    this.errorMessage = errorMessage;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    OAuthErrorResponse oauthErrorResponse = (OAuthErrorResponse) o;
    return Objects.equals(this.errorDomain, oauthErrorResponse.errorDomain) &&
        Objects.equals(this.errorTitle, oauthErrorResponse.errorTitle) &&
        Objects.equals(this.errorCode, oauthErrorResponse.errorCode) &&
        Objects.equals(this.developerMessage, oauthErrorResponse.developerMessage) &&
        Objects.equals(this.errorMessage, oauthErrorResponse.errorMessage);
  }

  @Override
  public int hashCode() {
    return Objects.hash(errorDomain, errorTitle, errorCode, developerMessage, errorMessage);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class OAuthErrorResponse {\n");
    
    sb.append("    errorDomain: ").append(toIndentedString(errorDomain)).append("\n");
    sb.append("    errorTitle: ").append(toIndentedString(errorTitle)).append("\n");
    sb.append("    errorCode: ").append(toIndentedString(errorCode)).append("\n");
    sb.append("    developerMessage: ").append(toIndentedString(developerMessage)).append("\n");
    sb.append("    errorMessage: ").append(toIndentedString(errorMessage)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

