/*
 * Network Edge APIs
 * API Documentation for NE's Beta APIs. More information about Network Edge marketplace & NE platform can be found [here](https://ecxfabric-documentation.equinix.com/hc/en-us/articles/360021809172-Enterprise-Network-Edge-Beta-Program-Introduction).
 *
 * OpenAPI spec version: General Availability
 * Contact: Network-Edge-Support@equinix.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.equinix.networkedge.model;

import java.util.Objects;

import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModelProperty;
import com.equinix.networkedge.model.MetroAccountResponse;

import java.util.ArrayList;
import java.util.List;

/**
 * PageResponseDtoMetroAccountResponse
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2019-06-20T13:45:54.773-07:00")
public class PageResponseDtoMetroAccountResponse {
  @SerializedName("accountCreateUrl")
  private String accountCreateUrl = null;

  @SerializedName("content")
  private List<MetroAccountResponse> content = null;

  @SerializedName("totalCount")
  private Long totalCount = null;

  @SerializedName("errorMessage")
  private String errorMessage = null;

  @SerializedName("errorCode")
  private String errorCode = null;

  public PageResponseDtoMetroAccountResponse accountCreateUrl(String accountCreateUrl) {
    this.accountCreateUrl = accountCreateUrl;
    return this;
  }

   /**
   * accountCreateUrl
   * @return accountCreateUrl
  **/
  @ApiModelProperty(value = "accountCreateUrl")
  public String getAccountCreateUrl() {
    return accountCreateUrl;
  }

  public void setAccountCreateUrl(String accountCreateUrl) {
    this.accountCreateUrl = accountCreateUrl;
  }

  public PageResponseDtoMetroAccountResponse content(List<MetroAccountResponse> content) {
    this.content = content;
    return this;
  }

  public PageResponseDtoMetroAccountResponse addContentItem(MetroAccountResponse contentItem) {
    if (this.content == null) {
      this.content = new ArrayList<MetroAccountResponse>();
    }
    this.content.add(contentItem);
    return this;
  }

   /**
   * Get content
   * @return content
  **/
  @ApiModelProperty(value = "")
  public List<MetroAccountResponse> getContent() {
    return content;
  }

  public void setContent(List<MetroAccountResponse> content) {
    this.content = content;
  }

  public PageResponseDtoMetroAccountResponse totalCount(Long totalCount) {
    this.totalCount = totalCount;
    return this;
  }

   /**
   * Total count
   * @return totalCount
  **/
  @ApiModelProperty(value = "Total count")
  public Long getTotalCount() {
    return totalCount;
  }

  public void setTotalCount(Long totalCount) {
    this.totalCount = totalCount;
  }

  public PageResponseDtoMetroAccountResponse errorMessage(String errorMessage) {
    this.errorMessage = errorMessage;
    return this;
  }

   /**
   * error Message
   * @return errorMessage
  **/
  @ApiModelProperty(value = "error Message")
  public String getErrorMessage() {
    return errorMessage;
  }

  public void setErrorMessage(String errorMessage) {
    this.errorMessage = errorMessage;
  }

  public PageResponseDtoMetroAccountResponse errorCode(String errorCode) {
    this.errorCode = errorCode;
    return this;
  }

   /**
   * error Code
   * @return errorCode
  **/
  @ApiModelProperty(value = "error Code")
  public String getErrorCode() {
    return errorCode;
  }

  public void setErrorCode(String errorCode) {
    this.errorCode = errorCode;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    PageResponseDtoMetroAccountResponse pageResponseDtoMetroAccountResponse = (PageResponseDtoMetroAccountResponse) o;
    return Objects.equals(this.accountCreateUrl, pageResponseDtoMetroAccountResponse.accountCreateUrl) &&
        Objects.equals(this.content, pageResponseDtoMetroAccountResponse.content) &&
        Objects.equals(this.totalCount, pageResponseDtoMetroAccountResponse.totalCount) &&
        Objects.equals(this.errorMessage, pageResponseDtoMetroAccountResponse.errorMessage) &&
        Objects.equals(this.errorCode, pageResponseDtoMetroAccountResponse.errorCode);
  }

  @Override
  public int hashCode() {
    return Objects.hash(accountCreateUrl, content, totalCount, errorMessage, errorCode);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class PageResponseDtoMetroAccountResponse {\n");
    
    sb.append("    accountCreateUrl: ").append(toIndentedString(accountCreateUrl)).append("\n");
    sb.append("    content: ").append(toIndentedString(content)).append("\n");
    sb.append("    totalCount: ").append(toIndentedString(totalCount)).append("\n");
    sb.append("    errorMessage: ").append(toIndentedString(errorMessage)).append("\n");
    sb.append("    errorCode: ").append(toIndentedString(errorCode)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

