/*
 * Network Edge APIs
 * API Documentation for NE's Beta APIs. More information about Network Edge marketplace & NE platform can be found [here](https://ecxfabric-documentation.equinix.com/hc/en-us/articles/360021809172-Enterprise-Network-Edge-Beta-Program-Introduction).
 *
 * OpenAPI spec version: General Availability
 * Contact: Network-Edge-Support@equinix.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.equinix.networkedge.model;

import java.util.Objects;

import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModelProperty;

/**
 * PostConnectionResponse
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2019-06-20T13:45:54.773-07:00")
public class PostConnectionResponse {
  @SerializedName("message")
  private String message = null;

  @SerializedName("primaryConnectionId")
  private String primaryConnectionId = null;

  @SerializedName("secondaryConnectionId")
  private String secondaryConnectionId = null;

  @SerializedName("status")
  private String status = null;

  public PostConnectionResponse message(String message) {
    this.message = message;
    return this;
  }

   /**
   * Get message
   * @return message
  **/
  @ApiModelProperty(example = "Connection created successfully", value = "")
  public String getMessage() {
    return message;
  }

  public void setMessage(String message) {
    this.message = message;
  }

  public PostConnectionResponse primaryConnectionId(String primaryConnectionId) {
    this.primaryConnectionId = primaryConnectionId;
    return this;
  }

   /**
   * Get primaryConnectionId
   * @return primaryConnectionId
  **/
  @ApiModelProperty(example = "xxxxx191-xx70-xxxx-xx04-xxxxxxxa37xx", value = "")
  public String getPrimaryConnectionId() {
    return primaryConnectionId;
  }

  public void setPrimaryConnectionId(String primaryConnectionId) {
    this.primaryConnectionId = primaryConnectionId;
  }

  public PostConnectionResponse secondaryConnectionId(String secondaryConnectionId) {
    this.secondaryConnectionId = secondaryConnectionId;
    return this;
  }

   /**
   * Get secondaryConnectionId
   * @return secondaryConnectionId
  **/
  @ApiModelProperty(example = "xxxxx191-xx70-xxxx-xx04-xxxxxxxa37xx", value = "")
  public String getSecondaryConnectionId() {
    return secondaryConnectionId;
  }

  public void setSecondaryConnectionId(String secondaryConnectionId) {
    this.secondaryConnectionId = secondaryConnectionId;
  }

  public PostConnectionResponse status(String status) {
    this.status = status;
    return this;
  }

   /**
   * Get status
   * @return status
  **/
  @ApiModelProperty(example = "SUCCESS", value = "")
  public String getStatus() {
    return status;
  }

  public void setStatus(String status) {
    this.status = status;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    PostConnectionResponse postConnectionResponse = (PostConnectionResponse) o;
    return Objects.equals(this.message, postConnectionResponse.message) &&
        Objects.equals(this.primaryConnectionId, postConnectionResponse.primaryConnectionId) &&
        Objects.equals(this.secondaryConnectionId, postConnectionResponse.secondaryConnectionId) &&
        Objects.equals(this.status, postConnectionResponse.status);
  }

  @Override
  public int hashCode() {
    return Objects.hash(message, primaryConnectionId, secondaryConnectionId, status);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class PostConnectionResponse {\n");
    
    sb.append("    message: ").append(toIndentedString(message)).append("\n");
    sb.append("    primaryConnectionId: ").append(toIndentedString(primaryConnectionId)).append("\n");
    sb.append("    secondaryConnectionId: ").append(toIndentedString(secondaryConnectionId)).append("\n");
    sb.append("    status: ").append(toIndentedString(status)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

