/*
 * Network Edge APIs
 * API Documentation for NE's Beta APIs. More information about Network Edge marketplace & NE platform can be found [here](https://ecxfabric-documentation.equinix.com/hc/en-us/articles/360021809172-Enterprise-Network-Edge-Beta-Program-Introduction).
 *
 * OpenAPI spec version: General Availability
 * Contact: Network-Edge-Support@equinix.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.equinix.networkedge.model;

import java.util.Objects;

import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModelProperty;

import java.util.ArrayList;
import java.util.List;

/**
 * PostConnectionRequest
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2019-06-20T13:45:54.773-07:00")
public class PostConnectionRequest {
  @SerializedName("primaryName")
  private String primaryName = null;

  @SerializedName("virtualDeviceUUID")
  private String virtualDeviceUUID = null;

  @SerializedName("profileUUID")
  private String profileUUID = null;

  @SerializedName("authorizationKey")
  private String authorizationKey = null;

  @SerializedName("speed")
  private Integer speed = null;

  @SerializedName("speedUnit")
  private String speedUnit = null;

  @SerializedName("notifications")
  private List<String> notifications = null;

  @SerializedName("purchaseOrderNumber")
  private String purchaseOrderNumber = null;

  @SerializedName("sellerRegion")
  private String sellerRegion = null;

  @SerializedName("sellerMetroCode")
  private String sellerMetroCode = null;

  @SerializedName("secondaryName")
  private String secondaryName = null;

  @SerializedName("namedTag")
  private String namedTag = null;

  @SerializedName("secondaryVirtualDeviceUUID")
  private String secondaryVirtualDeviceUUID = null;

  @SerializedName("secondaryProfileUUID")
  private String secondaryProfileUUID = null;

  @SerializedName("secondaryAuthorizationKey")
  private String secondaryAuthorizationKey = null;

  @SerializedName("secondarySellerRegion")
  private String secondarySellerRegion = null;

  @SerializedName("secondarySellerMetroCode")
  private String secondarySellerMetroCode = null;

  @SerializedName("secondarySpeed")
  private Integer secondarySpeed = null;

  @SerializedName("secondarySpeedUnit")
  private String secondarySpeedUnit = null;

  @SerializedName("secondaryNotifications")
  private List<String> secondaryNotifications = null;

  @SerializedName("primaryZSideVlanCTag")
  private Integer primaryZSideVlanCTag = null;

  @SerializedName("secondaryZSideVlanCTag")
  private Integer secondaryZSideVlanCTag = null;

  @SerializedName("primaryZSidePortUUID")
  private String primaryZSidePortUUID = null;

  @SerializedName("primaryZSideVlanSTag")
  private Integer primaryZSideVlanSTag = null;

  @SerializedName("secondaryZSidePortUUID")
  private String secondaryZSidePortUUID = null;

  @SerializedName("secondaryZSideVlanSTag")
  private Integer secondaryZSideVlanSTag = null;

  public PostConnectionRequest primaryName(String primaryName) {
    this.primaryName = primaryName;
    return this;
  }

   /**
   * Get primaryName
   * @return primaryName
  **/
  @ApiModelProperty(example = "v3-api-test-pri", value = "")
  public String getPrimaryName() {
    return primaryName;
  }

  public void setPrimaryName(String primaryName) {
    this.primaryName = primaryName;
  }

  public PostConnectionRequest virtualDeviceUUID(String virtualDeviceUUID) {
    this.virtualDeviceUUID = virtualDeviceUUID;
    return this;
  }

   /**
   * Get virtualDeviceUUID
   * @return virtualDeviceUUID
  **/
  @ApiModelProperty(example = "xxxxx191-xx70-xxxx-xx04-xxxxxxxa37xx", value = "")
  public String getVirtualDeviceUUID() {
    return virtualDeviceUUID;
  }

  public void setVirtualDeviceUUID(String virtualDeviceUUID) {
    this.virtualDeviceUUID = virtualDeviceUUID;
  }

  public PostConnectionRequest profileUUID(String profileUUID) {
    this.profileUUID = profileUUID;
    return this;
  }

   /**
   * Get profileUUID
   * @return profileUUID
  **/
  @ApiModelProperty(example = "xxxxx191-xx70-xxxx-xx04-xxxxxxxa37xx", value = "")
  public String getProfileUUID() {
    return profileUUID;
  }

  public void setProfileUUID(String profileUUID) {
    this.profileUUID = profileUUID;
  }

  public PostConnectionRequest authorizationKey(String authorizationKey) {
    this.authorizationKey = authorizationKey;
    return this;
  }

   /**
   * Get authorizationKey
   * @return authorizationKey
  **/
  @ApiModelProperty(example = "444111000222", value = "")
  public String getAuthorizationKey() {
    return authorizationKey;
  }

  public void setAuthorizationKey(String authorizationKey) {
    this.authorizationKey = authorizationKey;
  }

  public PostConnectionRequest speed(Integer speed) {
    this.speed = speed;
    return this;
  }

   /**
   * Get speed
   * @return speed
  **/
  @ApiModelProperty(example = "50", value = "")
  public Integer getSpeed() {
    return speed;
  }

  public void setSpeed(Integer speed) {
    this.speed = speed;
  }

  public PostConnectionRequest speedUnit(String speedUnit) {
    this.speedUnit = speedUnit;
    return this;
  }

   /**
   * Get speedUnit
   * @return speedUnit
  **/
  @ApiModelProperty(example = "MB", value = "")
  public String getSpeedUnit() {
    return speedUnit;
  }

  public void setSpeedUnit(String speedUnit) {
    this.speedUnit = speedUnit;
  }

  public PostConnectionRequest notifications(List<String> notifications) {
    this.notifications = notifications;
    return this;
  }

  public PostConnectionRequest addNotificationsItem(String notificationsItem) {
    if (this.notifications == null) {
      this.notifications = new ArrayList<String>();
    }
    this.notifications.add(notificationsItem);
    return this;
  }

   /**
   * Get notifications
   * @return notifications
  **/
  @ApiModelProperty(value = "")
  public List<String> getNotifications() {
    return notifications;
  }

  public void setNotifications(List<String> notifications) {
    this.notifications = notifications;
  }

  public PostConnectionRequest purchaseOrderNumber(String purchaseOrderNumber) {
    this.purchaseOrderNumber = purchaseOrderNumber;
    return this;
  }

   /**
   * Get purchaseOrderNumber
   * @return purchaseOrderNumber
  **/
  @ApiModelProperty(example = "312456323", value = "")
  public String getPurchaseOrderNumber() {
    return purchaseOrderNumber;
  }

  public void setPurchaseOrderNumber(String purchaseOrderNumber) {
    this.purchaseOrderNumber = purchaseOrderNumber;
  }

  public PostConnectionRequest sellerRegion(String sellerRegion) {
    this.sellerRegion = sellerRegion;
    return this;
  }

   /**
   * Get sellerRegion
   * @return sellerRegion
  **/
  @ApiModelProperty(example = "us-west-1", value = "")
  public String getSellerRegion() {
    return sellerRegion;
  }

  public void setSellerRegion(String sellerRegion) {
    this.sellerRegion = sellerRegion;
  }

  public PostConnectionRequest sellerMetroCode(String sellerMetroCode) {
    this.sellerMetroCode = sellerMetroCode;
    return this;
  }

   /**
   * Get sellerMetroCode
   * @return sellerMetroCode
  **/
  @ApiModelProperty(example = "SV", value = "")
  public String getSellerMetroCode() {
    return sellerMetroCode;
  }

  public void setSellerMetroCode(String sellerMetroCode) {
    this.sellerMetroCode = sellerMetroCode;
  }

  public PostConnectionRequest secondaryName(String secondaryName) {
    this.secondaryName = secondaryName;
    return this;
  }

   /**
   * Get secondaryName
   * @return secondaryName
  **/
  @ApiModelProperty(example = "v3-api-test-sec1", value = "")
  public String getSecondaryName() {
    return secondaryName;
  }

  public void setSecondaryName(String secondaryName) {
    this.secondaryName = secondaryName;
  }

  public PostConnectionRequest namedTag(String namedTag) {
    this.namedTag = namedTag;
    return this;
  }

   /**
   * Get namedTag
   * @return namedTag
  **/
  @ApiModelProperty(example = "Private", value = "")
  public String getNamedTag() {
    return namedTag;
  }

  public void setNamedTag(String namedTag) {
    this.namedTag = namedTag;
  }

  public PostConnectionRequest secondaryVirtualDeviceUUID(String secondaryVirtualDeviceUUID) {
    this.secondaryVirtualDeviceUUID = secondaryVirtualDeviceUUID;
    return this;
  }

   /**
   * Get secondaryVirtualDeviceUUID
   * @return secondaryVirtualDeviceUUID
  **/
  @ApiModelProperty(example = "xxxxx191-xx70-xxxx-xx04-xxxxxxxa37xx", value = "")
  public String getSecondaryVirtualDeviceUUID() {
    return secondaryVirtualDeviceUUID;
  }

  public void setSecondaryVirtualDeviceUUID(String secondaryVirtualDeviceUUID) {
    this.secondaryVirtualDeviceUUID = secondaryVirtualDeviceUUID;
  }

  public PostConnectionRequest secondaryProfileUUID(String secondaryProfileUUID) {
    this.secondaryProfileUUID = secondaryProfileUUID;
    return this;
  }

   /**
   * Get secondaryProfileUUID
   * @return secondaryProfileUUID
  **/
  @ApiModelProperty(example = "xxxxx191-xx70-xxxx-xx04-xxxxxxxa37xx", value = "")
  public String getSecondaryProfileUUID() {
    return secondaryProfileUUID;
  }

  public void setSecondaryProfileUUID(String secondaryProfileUUID) {
    this.secondaryProfileUUID = secondaryProfileUUID;
  }

  public PostConnectionRequest secondaryAuthorizationKey(String secondaryAuthorizationKey) {
    this.secondaryAuthorizationKey = secondaryAuthorizationKey;
    return this;
  }

   /**
   * Get secondaryAuthorizationKey
   * @return secondaryAuthorizationKey
  **/
  @ApiModelProperty(example = "444111000222", value = "")
  public String getSecondaryAuthorizationKey() {
    return secondaryAuthorizationKey;
  }

  public void setSecondaryAuthorizationKey(String secondaryAuthorizationKey) {
    this.secondaryAuthorizationKey = secondaryAuthorizationKey;
  }

  public PostConnectionRequest secondarySellerRegion(String secondarySellerRegion) {
    this.secondarySellerRegion = secondarySellerRegion;
    return this;
  }

   /**
   * Get secondarySellerRegion
   * @return secondarySellerRegion
  **/
  @ApiModelProperty(example = "us-west-1", value = "")
  public String getSecondarySellerRegion() {
    return secondarySellerRegion;
  }

  public void setSecondarySellerRegion(String secondarySellerRegion) {
    this.secondarySellerRegion = secondarySellerRegion;
  }

  public PostConnectionRequest secondarySellerMetroCode(String secondarySellerMetroCode) {
    this.secondarySellerMetroCode = secondarySellerMetroCode;
    return this;
  }

   /**
   * Get secondarySellerMetroCode
   * @return secondarySellerMetroCode
  **/
  @ApiModelProperty(example = "SV", value = "")
  public String getSecondarySellerMetroCode() {
    return secondarySellerMetroCode;
  }

  public void setSecondarySellerMetroCode(String secondarySellerMetroCode) {
    this.secondarySellerMetroCode = secondarySellerMetroCode;
  }

  public PostConnectionRequest secondarySpeed(Integer secondarySpeed) {
    this.secondarySpeed = secondarySpeed;
    return this;
  }

   /**
   * Get secondarySpeed
   * @return secondarySpeed
  **/
  @ApiModelProperty(example = "50", value = "")
  public Integer getSecondarySpeed() {
    return secondarySpeed;
  }

  public void setSecondarySpeed(Integer secondarySpeed) {
    this.secondarySpeed = secondarySpeed;
  }

  public PostConnectionRequest secondarySpeedUnit(String secondarySpeedUnit) {
    this.secondarySpeedUnit = secondarySpeedUnit;
    return this;
  }

   /**
   * Get secondarySpeedUnit
   * @return secondarySpeedUnit
  **/
  @ApiModelProperty(example = "MB", value = "")
  public String getSecondarySpeedUnit() {
    return secondarySpeedUnit;
  }

  public void setSecondarySpeedUnit(String secondarySpeedUnit) {
    this.secondarySpeedUnit = secondarySpeedUnit;
  }

  public PostConnectionRequest secondaryNotifications(List<String> secondaryNotifications) {
    this.secondaryNotifications = secondaryNotifications;
    return this;
  }

  public PostConnectionRequest addSecondaryNotificationsItem(String secondaryNotificationsItem) {
    if (this.secondaryNotifications == null) {
      this.secondaryNotifications = new ArrayList<String>();
    }
    this.secondaryNotifications.add(secondaryNotificationsItem);
    return this;
  }

   /**
   * Get secondaryNotifications
   * @return secondaryNotifications
  **/
  @ApiModelProperty(value = "")
  public List<String> getSecondaryNotifications() {
    return secondaryNotifications;
  }

  public void setSecondaryNotifications(List<String> secondaryNotifications) {
    this.secondaryNotifications = secondaryNotifications;
  }

  public PostConnectionRequest primaryZSideVlanCTag(Integer primaryZSideVlanCTag) {
    this.primaryZSideVlanCTag = primaryZSideVlanCTag;
    return this;
  }

   /**
   * Get primaryZSideVlanCTag
   * @return primaryZSideVlanCTag
  **/
  @ApiModelProperty(example = "101", value = "")
  public Integer getPrimaryZSideVlanCTag() {
    return primaryZSideVlanCTag;
  }

  public void setPrimaryZSideVlanCTag(Integer primaryZSideVlanCTag) {
    this.primaryZSideVlanCTag = primaryZSideVlanCTag;
  }

  public PostConnectionRequest secondaryZSideVlanCTag(Integer secondaryZSideVlanCTag) {
    this.secondaryZSideVlanCTag = secondaryZSideVlanCTag;
    return this;
  }

   /**
   * Get secondaryZSideVlanCTag
   * @return secondaryZSideVlanCTag
  **/
  @ApiModelProperty(example = "102", value = "")
  public Integer getSecondaryZSideVlanCTag() {
    return secondaryZSideVlanCTag;
  }

  public void setSecondaryZSideVlanCTag(Integer secondaryZSideVlanCTag) {
    this.secondaryZSideVlanCTag = secondaryZSideVlanCTag;
  }

  public PostConnectionRequest primaryZSidePortUUID(String primaryZSidePortUUID) {
    this.primaryZSidePortUUID = primaryZSidePortUUID;
    return this;
  }

   /**
   * Get primaryZSidePortUUID
   * @return primaryZSidePortUUID
  **/
  @ApiModelProperty(example = "xxxxx191-xx70-xxxx-xx04-xxxxxxxa37xx", value = "")
  public String getPrimaryZSidePortUUID() {
    return primaryZSidePortUUID;
  }

  public void setPrimaryZSidePortUUID(String primaryZSidePortUUID) {
    this.primaryZSidePortUUID = primaryZSidePortUUID;
  }

  public PostConnectionRequest primaryZSideVlanSTag(Integer primaryZSideVlanSTag) {
    this.primaryZSideVlanSTag = primaryZSideVlanSTag;
    return this;
  }

   /**
   * Get primaryZSideVlanSTag
   * @return primaryZSideVlanSTag
  **/
  @ApiModelProperty(example = "301", value = "")
  public Integer getPrimaryZSideVlanSTag() {
    return primaryZSideVlanSTag;
  }

  public void setPrimaryZSideVlanSTag(Integer primaryZSideVlanSTag) {
    this.primaryZSideVlanSTag = primaryZSideVlanSTag;
  }

  public PostConnectionRequest secondaryZSidePortUUID(String secondaryZSidePortUUID) {
    this.secondaryZSidePortUUID = secondaryZSidePortUUID;
    return this;
  }

   /**
   * Get secondaryZSidePortUUID
   * @return secondaryZSidePortUUID
  **/
  @ApiModelProperty(example = "xxxxx192-xx70-xxxx-xx04-xxxxxxxa37xx", value = "")
  public String getSecondaryZSidePortUUID() {
    return secondaryZSidePortUUID;
  }

  public void setSecondaryZSidePortUUID(String secondaryZSidePortUUID) {
    this.secondaryZSidePortUUID = secondaryZSidePortUUID;
  }

  public PostConnectionRequest secondaryZSideVlanSTag(Integer secondaryZSideVlanSTag) {
    this.secondaryZSideVlanSTag = secondaryZSideVlanSTag;
    return this;
  }

   /**
   * Get secondaryZSideVlanSTag
   * @return secondaryZSideVlanSTag
  **/
  @ApiModelProperty(example = "302", value = "")
  public Integer getSecondaryZSideVlanSTag() {
    return secondaryZSideVlanSTag;
  }

  public void setSecondaryZSideVlanSTag(Integer secondaryZSideVlanSTag) {
    this.secondaryZSideVlanSTag = secondaryZSideVlanSTag;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    PostConnectionRequest postConnectionRequest = (PostConnectionRequest) o;
    return Objects.equals(this.primaryName, postConnectionRequest.primaryName) &&
        Objects.equals(this.virtualDeviceUUID, postConnectionRequest.virtualDeviceUUID) &&
        Objects.equals(this.profileUUID, postConnectionRequest.profileUUID) &&
        Objects.equals(this.authorizationKey, postConnectionRequest.authorizationKey) &&
        Objects.equals(this.speed, postConnectionRequest.speed) &&
        Objects.equals(this.speedUnit, postConnectionRequest.speedUnit) &&
        Objects.equals(this.notifications, postConnectionRequest.notifications) &&
        Objects.equals(this.purchaseOrderNumber, postConnectionRequest.purchaseOrderNumber) &&
        Objects.equals(this.sellerRegion, postConnectionRequest.sellerRegion) &&
        Objects.equals(this.sellerMetroCode, postConnectionRequest.sellerMetroCode) &&
        Objects.equals(this.secondaryName, postConnectionRequest.secondaryName) &&
        Objects.equals(this.namedTag, postConnectionRequest.namedTag) &&
        Objects.equals(this.secondaryVirtualDeviceUUID, postConnectionRequest.secondaryVirtualDeviceUUID) &&
        Objects.equals(this.secondaryProfileUUID, postConnectionRequest.secondaryProfileUUID) &&
        Objects.equals(this.secondaryAuthorizationKey, postConnectionRequest.secondaryAuthorizationKey) &&
        Objects.equals(this.secondarySellerRegion, postConnectionRequest.secondarySellerRegion) &&
        Objects.equals(this.secondarySellerMetroCode, postConnectionRequest.secondarySellerMetroCode) &&
        Objects.equals(this.secondarySpeed, postConnectionRequest.secondarySpeed) &&
        Objects.equals(this.secondarySpeedUnit, postConnectionRequest.secondarySpeedUnit) &&
        Objects.equals(this.secondaryNotifications, postConnectionRequest.secondaryNotifications) &&
        Objects.equals(this.primaryZSideVlanCTag, postConnectionRequest.primaryZSideVlanCTag) &&
        Objects.equals(this.secondaryZSideVlanCTag, postConnectionRequest.secondaryZSideVlanCTag) &&
        Objects.equals(this.primaryZSidePortUUID, postConnectionRequest.primaryZSidePortUUID) &&
        Objects.equals(this.primaryZSideVlanSTag, postConnectionRequest.primaryZSideVlanSTag) &&
        Objects.equals(this.secondaryZSidePortUUID, postConnectionRequest.secondaryZSidePortUUID) &&
        Objects.equals(this.secondaryZSideVlanSTag, postConnectionRequest.secondaryZSideVlanSTag);
  }

  @Override
  public int hashCode() {
    return Objects.hash(primaryName, virtualDeviceUUID, profileUUID, authorizationKey, speed, speedUnit, notifications, purchaseOrderNumber, sellerRegion, sellerMetroCode, secondaryName, namedTag, secondaryVirtualDeviceUUID, secondaryProfileUUID, secondaryAuthorizationKey, secondarySellerRegion, secondarySellerMetroCode, secondarySpeed, secondarySpeedUnit, secondaryNotifications, primaryZSideVlanCTag, secondaryZSideVlanCTag, primaryZSidePortUUID, primaryZSideVlanSTag, secondaryZSidePortUUID, secondaryZSideVlanSTag);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class PostConnectionRequest {\n");
    
    sb.append("    primaryName: ").append(toIndentedString(primaryName)).append("\n");
    sb.append("    virtualDeviceUUID: ").append(toIndentedString(virtualDeviceUUID)).append("\n");
    sb.append("    profileUUID: ").append(toIndentedString(profileUUID)).append("\n");
    sb.append("    authorizationKey: ").append(toIndentedString(authorizationKey)).append("\n");
    sb.append("    speed: ").append(toIndentedString(speed)).append("\n");
    sb.append("    speedUnit: ").append(toIndentedString(speedUnit)).append("\n");
    sb.append("    notifications: ").append(toIndentedString(notifications)).append("\n");
    sb.append("    purchaseOrderNumber: ").append(toIndentedString(purchaseOrderNumber)).append("\n");
    sb.append("    sellerRegion: ").append(toIndentedString(sellerRegion)).append("\n");
    sb.append("    sellerMetroCode: ").append(toIndentedString(sellerMetroCode)).append("\n");
    sb.append("    secondaryName: ").append(toIndentedString(secondaryName)).append("\n");
    sb.append("    namedTag: ").append(toIndentedString(namedTag)).append("\n");
    sb.append("    secondaryVirtualDeviceUUID: ").append(toIndentedString(secondaryVirtualDeviceUUID)).append("\n");
    sb.append("    secondaryProfileUUID: ").append(toIndentedString(secondaryProfileUUID)).append("\n");
    sb.append("    secondaryAuthorizationKey: ").append(toIndentedString(secondaryAuthorizationKey)).append("\n");
    sb.append("    secondarySellerRegion: ").append(toIndentedString(secondarySellerRegion)).append("\n");
    sb.append("    secondarySellerMetroCode: ").append(toIndentedString(secondarySellerMetroCode)).append("\n");
    sb.append("    secondarySpeed: ").append(toIndentedString(secondarySpeed)).append("\n");
    sb.append("    secondarySpeedUnit: ").append(toIndentedString(secondarySpeedUnit)).append("\n");
    sb.append("    secondaryNotifications: ").append(toIndentedString(secondaryNotifications)).append("\n");
    sb.append("    primaryZSideVlanCTag: ").append(toIndentedString(primaryZSideVlanCTag)).append("\n");
    sb.append("    secondaryZSideVlanCTag: ").append(toIndentedString(secondaryZSideVlanCTag)).append("\n");
    sb.append("    primaryZSidePortUUID: ").append(toIndentedString(primaryZSidePortUUID)).append("\n");
    sb.append("    primaryZSideVlanSTag: ").append(toIndentedString(primaryZSideVlanSTag)).append("\n");
    sb.append("    secondaryZSidePortUUID: ").append(toIndentedString(secondaryZSidePortUUID)).append("\n");
    sb.append("    secondaryZSideVlanSTag: ").append(toIndentedString(secondaryZSideVlanSTag)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

