/*
 * Network Edge APIs
 * API Documentation for NE's Beta APIs. More information about Network Edge marketplace & NE platform can be found [here](https://ecxfabric-documentation.equinix.com/hc/en-us/articles/360021809172-Enterprise-Network-Edge-Beta-Program-Introduction).
 *
 * OpenAPI spec version: General Availability
 * Contact: Network-Edge-Support@equinix.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.equinix.networkedge.model;

import java.util.Objects;

import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModelProperty;

/**
 * SecondaryDeviceDeleteRequest
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2019-06-20T13:45:54.773-07:00")
public class SecondaryDeviceDeleteRequest {
  @SerializedName("deactivationKey")
  private String deactivationKey = null;

  public SecondaryDeviceDeleteRequest deactivationKey(String deactivationKey) {
    this.deactivationKey = deactivationKey;
    return this;
  }

   /**
   * Deactivation key for secondary device
   * @return deactivationKey
  **/
  @ApiModelProperty(example = "8dfbd5ba3610234d9e550032603cc34762af140533e2c1de0111d3451d16eefd", value = "Deactivation key for secondary device")
  public String getDeactivationKey() {
    return deactivationKey;
  }

  public void setDeactivationKey(String deactivationKey) {
    this.deactivationKey = deactivationKey;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    SecondaryDeviceDeleteRequest secondaryDeviceDeleteRequest = (SecondaryDeviceDeleteRequest) o;
    return Objects.equals(this.deactivationKey, secondaryDeviceDeleteRequest.deactivationKey);
  }

  @Override
  public int hashCode() {
    return Objects.hash(deactivationKey);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class SecondaryDeviceDeleteRequest {\n");
    
    sb.append("    deactivationKey: ").append(toIndentedString(deactivationKey)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

