/*
 * Network Edge APIs
 * API Documentation for NE's Beta APIs. More information about Network Edge marketplace & NE platform can be found [here](https://ecxfabric-documentation.equinix.com/hc/en-us/articles/360021809172-Enterprise-Network-Edge-Beta-Program-Introduction).
 *
 * OpenAPI spec version: General Availability
 * Contact: Network-Edge-Support@equinix.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.equinix.networkedge.model;

import java.util.Objects;

import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModelProperty;

import java.util.ArrayList;
import java.util.List;

/**
 * SshAccessUpdateRequest
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2019-06-20T13:45:54.773-07:00")
public class SshAccessUpdateRequest {
  @SerializedName("sshAcl")
  private List<Object> sshAcl = null;

  public SshAccessUpdateRequest sshAcl(List<Object> sshAcl) {
    this.sshAcl = sshAcl;
    return this;
  }

  public SshAccessUpdateRequest addSshAclItem(Object sshAclItem) {
    if (this.sshAcl == null) {
      this.sshAcl = new ArrayList<Object>();
    }
    this.sshAcl.add(sshAclItem);
    return this;
  }

   /**
   * Get sshAcl
   * @return sshAcl
  **/
  @ApiModelProperty(value = "")
  public List<Object> getSshAcl() {
    return sshAcl;
  }

  public void setSshAcl(List<Object> sshAcl) {
    this.sshAcl = sshAcl;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    SshAccessUpdateRequest sshAccessUpdateRequest = (SshAccessUpdateRequest) o;
    return Objects.equals(this.sshAcl, sshAccessUpdateRequest.sshAcl);
  }

  @Override
  public int hashCode() {
    return Objects.hash(sshAcl);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class SshAccessUpdateRequest {\n");
    
    sb.append("    sshAcl: ").append(toIndentedString(sshAcl)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

