/*
 * Network Edge APIs
 * API Documentation for NE's Beta APIs. More information about Network Edge marketplace & NE platform can be found [here](https://ecxfabric-documentation.equinix.com/hc/en-us/articles/360021809172-Enterprise-Network-Edge-Beta-Program-Introduction).
 *
 * OpenAPI spec version: General Availability
 * Contact: Network-Edge-Support@equinix.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.equinix.networkedge.model;

import java.util.Objects;

import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModelProperty;

/**
 * SshUserInfoDissociateResponse
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2019-06-20T13:45:54.773-07:00")
public class SshUserInfoDissociateResponse {
  @SerializedName("sshUserDeleted")
  private Boolean sshUserDeleted = null;

  public SshUserInfoDissociateResponse sshUserDeleted(Boolean sshUserDeleted) {
    this.sshUserDeleted = sshUserDeleted;
    return this;
  }

   /**
   * true &#x3D; the ssh user has been deleted since there are no more devices associated to this userfalse &#x3D; the ssh user has not been deleted since some associations to devices exist.
   * @return sshUserDeleted
  **/
  @ApiModelProperty(example = "false", value = "true = the ssh user has been deleted since there are no more devices associated to this userfalse = the ssh user has not been deleted since some associations to devices exist.")
  public Boolean isSshUserDeleted() {
    return sshUserDeleted;
  }

  public void setSshUserDeleted(Boolean sshUserDeleted) {
    this.sshUserDeleted = sshUserDeleted;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    SshUserInfoDissociateResponse sshUserInfoDissociateResponse = (SshUserInfoDissociateResponse) o;
    return Objects.equals(this.sshUserDeleted, sshUserInfoDissociateResponse.sshUserDeleted);
  }

  @Override
  public int hashCode() {
    return Objects.hash(sshUserDeleted);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class SshUserInfoDissociateResponse {\n");
    
    sb.append("    sshUserDeleted: ").append(toIndentedString(sshUserDeleted)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

