/*
 * Network Edge APIs
 * API Documentation for NE's Beta APIs. More information about Network Edge marketplace & NE platform can be found [here](https://ecxfabric-documentation.equinix.com/hc/en-us/articles/360021809172-Enterprise-Network-Edge-Beta-Program-Introduction).
 *
 * OpenAPI spec version: General Availability
 * Contact: Network-Edge-Support@equinix.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.equinix.networkedge.model;

import java.util.Objects;

import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModelProperty;

/**
 * VirtualDeviceUpdateRequest
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2019-06-20T13:45:54.773-07:00")
public class VirtualDeviceUpdateRequest {
  @SerializedName("virtualDeviceName")
  private String virtualDeviceName = null;

  public VirtualDeviceUpdateRequest virtualDeviceName(String virtualDeviceName) {
    this.virtualDeviceName = virtualDeviceName;
    return this;
  }

   /**
   * Virtual Device Name
   * @return virtualDeviceName
  **/
  @ApiModelProperty(example = "Router1-csr1000v", value = "Virtual Device Name")
  public String getVirtualDeviceName() {
    return virtualDeviceName;
  }

  public void setVirtualDeviceName(String virtualDeviceName) {
    this.virtualDeviceName = virtualDeviceName;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    VirtualDeviceUpdateRequest virtualDeviceUpdateRequest = (VirtualDeviceUpdateRequest) o;
    return Objects.equals(this.virtualDeviceName, virtualDeviceUpdateRequest.virtualDeviceName);
  }

  @Override
  public int hashCode() {
    return Objects.hash(virtualDeviceName);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class VirtualDeviceUpdateRequest {\n");
    
    sb.append("    virtualDeviceName: ").append(toIndentedString(virtualDeviceName)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

