/*
 * Network Edge APIs
 * API Documentation for NE's Beta APIs. More information about Network Edge marketplace & NE platform can be found [here](https://ecxfabric-documentation.equinix.com/hc/en-us/articles/360021809172-Enterprise-Network-Edge-Beta-Program-Introduction).
 *
 * OpenAPI spec version: General Availability
 * Contact: Network-Edge-Support@equinix.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.equinix.networkedge.model;

import java.util.Objects;

import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModelProperty;
import com.equinix.networkedge.model.SecondaryDeviceDeleteRequest;

/**
 * VirtualDeviceDeleteRequest
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2019-06-20T13:45:54.773-07:00")
public class VirtualDeviceDeleteRequest {
  @SerializedName("deactivationKey")
  private String deactivationKey = null;

  @SerializedName("secondary")
  private SecondaryDeviceDeleteRequest secondary = null;

  public VirtualDeviceDeleteRequest deactivationKey(String deactivationKey) {
    this.deactivationKey = deactivationKey;
    return this;
  }

   /**
   * Deactivation key for primary device
   * @return deactivationKey
  **/
  @ApiModelProperty(example = "8dfbd5ba3610234d9e550032603cc34762af140533e2c1de0111d3451d16eefd", value = "Deactivation key for primary device")
  public String getDeactivationKey() {
    return deactivationKey;
  }

  public void setDeactivationKey(String deactivationKey) {
    this.deactivationKey = deactivationKey;
  }

  public VirtualDeviceDeleteRequest secondary(SecondaryDeviceDeleteRequest secondary) {
    this.secondary = secondary;
    return this;
  }

   /**
   * Get secondary
   * @return secondary
  **/
  @ApiModelProperty(value = "")
  public SecondaryDeviceDeleteRequest getSecondary() {
    return secondary;
  }

  public void setSecondary(SecondaryDeviceDeleteRequest secondary) {
    this.secondary = secondary;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    VirtualDeviceDeleteRequest virtualDeviceDeleteRequest = (VirtualDeviceDeleteRequest) o;
    return Objects.equals(this.deactivationKey, virtualDeviceDeleteRequest.deactivationKey) &&
        Objects.equals(this.secondary, virtualDeviceDeleteRequest.secondary);
  }

  @Override
  public int hashCode() {
    return Objects.hash(deactivationKey, secondary);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class VirtualDeviceDeleteRequest {\n");
    
    sb.append("    deactivationKey: ").append(toIndentedString(deactivationKey)).append("\n");
    sb.append("    secondary: ").append(toIndentedString(secondary)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

