/*
 * Network Edge APIs
 * API Documentation for NE's Beta APIs. More information about Network Edge marketplace & NE platform can be found [here](https://ecxfabric-documentation.equinix.com/hc/en-us/articles/360021809172-Enterprise-Network-Edge-Beta-Program-Introduction).
 *
 * OpenAPI spec version: General Availability
 * Contact: Network-Edge-Support@equinix.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.equinix.networkedge.model;

import java.util.Objects;

import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModelProperty;

import java.util.ArrayList;
import java.util.List;

/**
 * VirtualDeviceResponse
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2019-06-20T13:45:54.773-07:00")
public class VirtualDeviceResponse {
  @SerializedName("accountName")
  private String accountName = null;

  @SerializedName("accountNumber")
  private String accountNumber = null;

  @SerializedName("createdBy")
  private String createdBy = null;

  @SerializedName("createdDate")
  private String createdDate = null;

  @SerializedName("deviceSerialNo")
  private String deviceSerialNo = null;

  @SerializedName("deviceTypeCategory")
  private String deviceTypeCategory = null;

  @SerializedName("deviceTypeCode")
  private String deviceTypeCode = null;

  @SerializedName("deviceTypeName")
  private String deviceTypeName = null;

  @SerializedName("expiry")
  private String expiry = null;

  @SerializedName("region")
  private String region = null;

  @SerializedName("deviceTypeVendor")
  private String deviceTypeVendor = null;

  @SerializedName("hostName")
  private String hostName = null;

  @SerializedName("id")
  private String id = null;

  @SerializedName("lastUpdatedBy")
  private String lastUpdatedBy = null;

  @SerializedName("lastUpdatedDate")
  private String lastUpdatedDate = null;

  @SerializedName("licenseFileId")
  private String licenseFileId = null;

  @SerializedName("licenseName")
  private String licenseName = null;

  @SerializedName("licenseStatus")
  private String licenseStatus = null;

  @SerializedName("licenseType")
  private String licenseType = null;

  @SerializedName("metroCode")
  private String metroCode = null;

  @SerializedName("metroName")
  private String metroName = null;

  @SerializedName("name")
  private String name = null;

  @SerializedName("notifications")
  private List<String> notifications = null;

  @SerializedName("packageCode")
  private String packageCode = null;

  @SerializedName("packageName")
  private String packageName = null;

  @SerializedName("purchaseOrderNumber")
  private String purchaseOrderNumber = null;

  @SerializedName("redundancyType")
  private String redundancyType = null;

  @SerializedName("redundantUUID")
  private String redundantUUID = null;

  @SerializedName("sshIpAddress")
  private String sshIpAddress = null;

  @SerializedName("sshIpFqdn")
  private String sshIpFqdn = null;

  @SerializedName("sshUsername")
  private String sshUsername = null;

  @SerializedName("status")
  private String status = null;

  @SerializedName("tenantName")
  private String tenantName = null;

  @SerializedName("throughput")
  private Integer throughput = null;

  @SerializedName("throughputUnit")
  private String throughputUnit = null;

  @SerializedName("sshAcl")
  private List<Object> sshAcl = null;

  @SerializedName("managementIp")
  private String managementIp = null;

  @SerializedName("managementGatewayIp")
  private String managementGatewayIp = null;

  @SerializedName("publicIp")
  private String publicIp = null;

  @SerializedName("publicGatewayIp")
  private String publicGatewayIp = null;

  @SerializedName("primaryDnsName")
  private String primaryDnsName = null;

  @SerializedName("secondaryDnsName")
  private String secondaryDnsName = null;

  @SerializedName("termLength")
  private String termLength = null;

  @SerializedName("additionalBandwidth")
  private String additionalBandwidth = null;

  @SerializedName("siteId")
  private String siteId = null;

  @SerializedName("systemIpAddress")
  private String systemIpAddress = null;

  public VirtualDeviceResponse accountName(String accountName) {
    this.accountName = accountName;
    return this;
  }

   /**
   * Get accountName
   * @return accountName
  **/
  @ApiModelProperty(example = "ABC INC", value = "")
  public String getAccountName() {
    return accountName;
  }

  public void setAccountName(String accountName) {
    this.accountName = accountName;
  }

  public VirtualDeviceResponse accountNumber(String accountNumber) {
    this.accountNumber = accountNumber;
    return this;
  }

   /**
   * Get accountNumber
   * @return accountNumber
  **/
  @ApiModelProperty(example = "133911", value = "")
  public String getAccountNumber() {
    return accountNumber;
  }

  public void setAccountNumber(String accountNumber) {
    this.accountNumber = accountNumber;
  }

  public VirtualDeviceResponse createdBy(String createdBy) {
    this.createdBy = createdBy;
    return this;
  }

   /**
   * Get createdBy
   * @return createdBy
  **/
  @ApiModelProperty(example = "cust0001", value = "")
  public String getCreatedBy() {
    return createdBy;
  }

  public void setCreatedBy(String createdBy) {
    this.createdBy = createdBy;
  }

  public VirtualDeviceResponse createdDate(String createdDate) {
    this.createdDate = createdDate;
    return this;
  }

   /**
   * Get createdDate
   * @return createdDate
  **/
  @ApiModelProperty(example = "2018-01-30T10:30:31.387Z", value = "")
  public String getCreatedDate() {
    return createdDate;
  }

  public void setCreatedDate(String createdDate) {
    this.createdDate = createdDate;
  }

  public VirtualDeviceResponse deviceSerialNo(String deviceSerialNo) {
    this.deviceSerialNo = deviceSerialNo;
    return this;
  }

   /**
   * Get deviceSerialNo
   * @return deviceSerialNo
  **/
  @ApiModelProperty(example = "53791666484", value = "")
  public String getDeviceSerialNo() {
    return deviceSerialNo;
  }

  public void setDeviceSerialNo(String deviceSerialNo) {
    this.deviceSerialNo = deviceSerialNo;
  }

  public VirtualDeviceResponse deviceTypeCategory(String deviceTypeCategory) {
    this.deviceTypeCategory = deviceTypeCategory;
    return this;
  }

   /**
   * Get deviceTypeCategory
   * @return deviceTypeCategory
  **/
  @ApiModelProperty(example = "ROUTER", value = "")
  public String getDeviceTypeCategory() {
    return deviceTypeCategory;
  }

  public void setDeviceTypeCategory(String deviceTypeCategory) {
    this.deviceTypeCategory = deviceTypeCategory;
  }

  public VirtualDeviceResponse deviceTypeCode(String deviceTypeCode) {
    this.deviceTypeCode = deviceTypeCode;
    return this;
  }

   /**
   * Get deviceTypeCode
   * @return deviceTypeCode
  **/
  @ApiModelProperty(example = "CSR1000V", value = "")
  public String getDeviceTypeCode() {
    return deviceTypeCode;
  }

  public void setDeviceTypeCode(String deviceTypeCode) {
    this.deviceTypeCode = deviceTypeCode;
  }

  public VirtualDeviceResponse deviceTypeName(String deviceTypeName) {
    this.deviceTypeName = deviceTypeName;
    return this;
  }

   /**
   * Get deviceTypeName
   * @return deviceTypeName
  **/
  @ApiModelProperty(example = "CSR 1000v", value = "")
  public String getDeviceTypeName() {
    return deviceTypeName;
  }

  public void setDeviceTypeName(String deviceTypeName) {
    this.deviceTypeName = deviceTypeName;
  }

  public VirtualDeviceResponse expiry(String expiry) {
    this.expiry = expiry;
    return this;
  }

   /**
   * Get expiry
   * @return expiry
  **/
  @ApiModelProperty(example = "2019-02-07T00:00:00.000+0000", value = "")
  public String getExpiry() {
    return expiry;
  }

  public void setExpiry(String expiry) {
    this.expiry = expiry;
  }

  public VirtualDeviceResponse region(String region) {
    this.region = region;
    return this;
  }

   /**
   * Get region
   * @return region
  **/
  @ApiModelProperty(example = "AMER", value = "")
  public String getRegion() {
    return region;
  }

  public void setRegion(String region) {
    this.region = region;
  }

  public VirtualDeviceResponse deviceTypeVendor(String deviceTypeVendor) {
    this.deviceTypeVendor = deviceTypeVendor;
    return this;
  }

   /**
   * Get deviceTypeVendor
   * @return deviceTypeVendor
  **/
  @ApiModelProperty(example = "Cisco", value = "")
  public String getDeviceTypeVendor() {
    return deviceTypeVendor;
  }

  public void setDeviceTypeVendor(String deviceTypeVendor) {
    this.deviceTypeVendor = deviceTypeVendor;
  }

  public VirtualDeviceResponse hostName(String hostName) {
    this.hostName = hostName;
    return this;
  }

   /**
   * Get hostName
   * @return hostName
  **/
  @ApiModelProperty(example = "VR-SV-CSR1000V-cust0001-1", value = "")
  public String getHostName() {
    return hostName;
  }

  public void setHostName(String hostName) {
    this.hostName = hostName;
  }

  public VirtualDeviceResponse id(String id) {
    this.id = id;
    return this;
  }

   /**
   * Get id
   * @return id
  **/
  @ApiModelProperty(example = "877a3aa2-c49a-4af1-98a6-007424e737ae", value = "")
  public String getId() {
    return id;
  }

  public void setId(String id) {
    this.id = id;
  }

  public VirtualDeviceResponse lastUpdatedBy(String lastUpdatedBy) {
    this.lastUpdatedBy = lastUpdatedBy;
    return this;
  }

   /**
   * Get lastUpdatedBy
   * @return lastUpdatedBy
  **/
  @ApiModelProperty(example = "cust0002", value = "")
  public String getLastUpdatedBy() {
    return lastUpdatedBy;
  }

  public void setLastUpdatedBy(String lastUpdatedBy) {
    this.lastUpdatedBy = lastUpdatedBy;
  }

  public VirtualDeviceResponse lastUpdatedDate(String lastUpdatedDate) {
    this.lastUpdatedDate = lastUpdatedDate;
    return this;
  }

   /**
   * Get lastUpdatedDate
   * @return lastUpdatedDate
  **/
  @ApiModelProperty(example = "2018-01-30T10:30:31.387Z", value = "")
  public String getLastUpdatedDate() {
    return lastUpdatedDate;
  }

  public void setLastUpdatedDate(String lastUpdatedDate) {
    this.lastUpdatedDate = lastUpdatedDate;
  }

  public VirtualDeviceResponse licenseFileId(String licenseFileId) {
    this.licenseFileId = licenseFileId;
    return this;
  }

   /**
   * Get licenseFileId
   * @return licenseFileId
  **/
  @ApiModelProperty(example = "877a3aa2-c49a-4af1-98a6-007424e737ae", value = "")
  public String getLicenseFileId() {
    return licenseFileId;
  }

  public void setLicenseFileId(String licenseFileId) {
    this.licenseFileId = licenseFileId;
  }

  public VirtualDeviceResponse licenseName(String licenseName) {
    this.licenseName = licenseName;
    return this;
  }

   /**
   * Get licenseName
   * @return licenseName
  **/
  @ApiModelProperty(example = "Bring your own license", value = "")
  public String getLicenseName() {
    return licenseName;
  }

  public void setLicenseName(String licenseName) {
    this.licenseName = licenseName;
  }

  public VirtualDeviceResponse licenseStatus(String licenseStatus) {
    this.licenseStatus = licenseStatus;
    return this;
  }

   /**
   * Get licenseStatus
   * @return licenseStatus
  **/
  @ApiModelProperty(example = "REGISTERED", value = "")
  public String getLicenseStatus() {
    return licenseStatus;
  }

  public void setLicenseStatus(String licenseStatus) {
    this.licenseStatus = licenseStatus;
  }

  public VirtualDeviceResponse licenseType(String licenseType) {
    this.licenseType = licenseType;
    return this;
  }

   /**
   * Get licenseType
   * @return licenseType
  **/
  @ApiModelProperty(example = "BYOL", value = "")
  public String getLicenseType() {
    return licenseType;
  }

  public void setLicenseType(String licenseType) {
    this.licenseType = licenseType;
  }

  public VirtualDeviceResponse metroCode(String metroCode) {
    this.metroCode = metroCode;
    return this;
  }

   /**
   * Get metroCode
   * @return metroCode
  **/
  @ApiModelProperty(example = "SV", value = "")
  public String getMetroCode() {
    return metroCode;
  }

  public void setMetroCode(String metroCode) {
    this.metroCode = metroCode;
  }

  public VirtualDeviceResponse metroName(String metroName) {
    this.metroName = metroName;
    return this;
  }

   /**
   * Get metroName
   * @return metroName
  **/
  @ApiModelProperty(example = "Silicon Valley", value = "")
  public String getMetroName() {
    return metroName;
  }

  public void setMetroName(String metroName) {
    this.metroName = metroName;
  }

  public VirtualDeviceResponse name(String name) {
    this.name = name;
    return this;
  }

   /**
   * Get name
   * @return name
  **/
  @ApiModelProperty(example = "AWS-Azure-Router-csr1000v", value = "")
  public String getName() {
    return name;
  }

  public void setName(String name) {
    this.name = name;
  }

  public VirtualDeviceResponse notifications(List<String> notifications) {
    this.notifications = notifications;
    return this;
  }

  public VirtualDeviceResponse addNotificationsItem(String notificationsItem) {
    if (this.notifications == null) {
      this.notifications = new ArrayList<String>();
    }
    this.notifications.add(notificationsItem);
    return this;
  }

   /**
   * Get notifications
   * @return notifications
  **/
  @ApiModelProperty(example = "[\"test@equinix.com\",\"test1@eqinix.com\"]", value = "")
  public List<String> getNotifications() {
    return notifications;
  }

  public void setNotifications(List<String> notifications) {
    this.notifications = notifications;
  }

  public VirtualDeviceResponse packageCode(String packageCode) {
    this.packageCode = packageCode;
    return this;
  }

   /**
   * Get packageCode
   * @return packageCode
  **/
  @ApiModelProperty(example = "IPBASE", value = "")
  public String getPackageCode() {
    return packageCode;
  }

  public void setPackageCode(String packageCode) {
    this.packageCode = packageCode;
  }

  public VirtualDeviceResponse packageName(String packageName) {
    this.packageName = packageName;
    return this;
  }

   /**
   * Get packageName
   * @return packageName
  **/
  @ApiModelProperty(example = "IPBASE", value = "")
  public String getPackageName() {
    return packageName;
  }

  public void setPackageName(String packageName) {
    this.packageName = packageName;
  }

  public VirtualDeviceResponse purchaseOrderNumber(String purchaseOrderNumber) {
    this.purchaseOrderNumber = purchaseOrderNumber;
    return this;
  }

   /**
   * Get purchaseOrderNumber
   * @return purchaseOrderNumber
  **/
  @ApiModelProperty(example = "PO1223", value = "")
  public String getPurchaseOrderNumber() {
    return purchaseOrderNumber;
  }

  public void setPurchaseOrderNumber(String purchaseOrderNumber) {
    this.purchaseOrderNumber = purchaseOrderNumber;
  }

  public VirtualDeviceResponse redundancyType(String redundancyType) {
    this.redundancyType = redundancyType;
    return this;
  }

   /**
   * Get redundancyType
   * @return redundancyType
  **/
  @ApiModelProperty(example = "PRIMARY", value = "")
  public String getRedundancyType() {
    return redundancyType;
  }

  public void setRedundancyType(String redundancyType) {
    this.redundancyType = redundancyType;
  }

  public VirtualDeviceResponse redundantUUID(String redundantUUID) {
    this.redundantUUID = redundantUUID;
    return this;
  }

   /**
   * Get redundantUUID
   * @return redundantUUID
  **/
  @ApiModelProperty(example = "xxxxx191-xx70-xxxx-xx04-xxxxxxxa67xx", value = "")
  public String getRedundantUUID() {
    return redundantUUID;
  }

  public void setRedundantUUID(String redundantUUID) {
    this.redundantUUID = redundantUUID;
  }

  public VirtualDeviceResponse sshIpAddress(String sshIpAddress) {
    this.sshIpAddress = sshIpAddress;
    return this;
  }

   /**
   * Get sshIpAddress
   * @return sshIpAddress
  **/
  @ApiModelProperty(example = "10.195.11.23", value = "")
  public String getSshIpAddress() {
    return sshIpAddress;
  }

  public void setSshIpAddress(String sshIpAddress) {
    this.sshIpAddress = sshIpAddress;
  }

  public VirtualDeviceResponse sshIpFqdn(String sshIpFqdn) {
    this.sshIpFqdn = sshIpFqdn;
    return this;
  }

   /**
   * Get sshIpFqdn
   * @return sshIpFqdn
  **/
  @ApiModelProperty(example = "test-device-168-201-97-149.eis.lab.equinix.com", value = "")
  public String getSshIpFqdn() {
    return sshIpFqdn;
  }

  public void setSshIpFqdn(String sshIpFqdn) {
    this.sshIpFqdn = sshIpFqdn;
  }

  public VirtualDeviceResponse sshUsername(String sshUsername) {
    this.sshUsername = sshUsername;
    return this;
  }

   /**
   * Get sshUsername
   * @return sshUsername
  **/
  @ApiModelProperty(example = "test0user", value = "")
  public String getSshUsername() {
    return sshUsername;
  }

  public void setSshUsername(String sshUsername) {
    this.sshUsername = sshUsername;
  }

  public VirtualDeviceResponse status(String status) {
    this.status = status;
    return this;
  }

   /**
   * Get status
   * @return status
  **/
  @ApiModelProperty(example = "PROVISIONED", value = "")
  public String getStatus() {
    return status;
  }

  public void setStatus(String status) {
    this.status = status;
  }

  public VirtualDeviceResponse tenantName(String tenantName) {
    this.tenantName = tenantName;
    return this;
  }

   /**
   * Get tenantName
   * @return tenantName
  **/
  @ApiModelProperty(example = "sv-9031", value = "")
  public String getTenantName() {
    return tenantName;
  }

  public void setTenantName(String tenantName) {
    this.tenantName = tenantName;
  }

  public VirtualDeviceResponse throughput(Integer throughput) {
    this.throughput = throughput;
    return this;
  }

   /**
   * Get throughput
   * @return throughput
  **/
  @ApiModelProperty(example = "500", value = "")
  public Integer getThroughput() {
    return throughput;
  }

  public void setThroughput(Integer throughput) {
    this.throughput = throughput;
  }

  public VirtualDeviceResponse throughputUnit(String throughputUnit) {
    this.throughputUnit = throughputUnit;
    return this;
  }

   /**
   * Get throughputUnit
   * @return throughputUnit
  **/
  @ApiModelProperty(example = "Mbps", value = "")
  public String getThroughputUnit() {
    return throughputUnit;
  }

  public void setThroughputUnit(String throughputUnit) {
    this.throughputUnit = throughputUnit;
  }

  public VirtualDeviceResponse sshAcl(List<Object> sshAcl) {
    this.sshAcl = sshAcl;
    return this;
  }

  public VirtualDeviceResponse addSshAclItem(Object sshAclItem) {
    if (this.sshAcl == null) {
      this.sshAcl = new ArrayList<Object>();
    }
    this.sshAcl.add(sshAclItem);
    return this;
  }

   /**
   * Get sshAcl
   * @return sshAcl
  **/
  @ApiModelProperty(example = "[\"192.168.1.1/32\",\"192.168.94.0/24\"]", value = "")
  public List<Object> getSshAcl() {
    return sshAcl;
  }

  public void setSshAcl(List<Object> sshAcl) {
    this.sshAcl = sshAcl;
  }

  public VirtualDeviceResponse managementIp(String managementIp) {
    this.managementIp = managementIp;
    return this;
  }

   /**
   * Get managementIp
   * @return managementIp
  **/
  @ApiModelProperty(example = "10.195.237.228/26", value = "")
  public String getManagementIp() {
    return managementIp;
  }

  public void setManagementIp(String managementIp) {
    this.managementIp = managementIp;
  }

  public VirtualDeviceResponse managementGatewayIp(String managementGatewayIp) {
    this.managementGatewayIp = managementGatewayIp;
    return this;
  }

   /**
   * Get managementGatewayIp
   * @return managementGatewayIp
  **/
  @ApiModelProperty(example = "10.195.237.254", value = "")
  public String getManagementGatewayIp() {
    return managementGatewayIp;
  }

  public void setManagementGatewayIp(String managementGatewayIp) {
    this.managementGatewayIp = managementGatewayIp;
  }

  public VirtualDeviceResponse publicIp(String publicIp) {
    this.publicIp = publicIp;
    return this;
  }

   /**
   * Get publicIp
   * @return publicIp
  **/
  @ApiModelProperty(example = "149.97.198.95/31", value = "")
  public String getPublicIp() {
    return publicIp;
  }

  public void setPublicIp(String publicIp) {
    this.publicIp = publicIp;
  }

  public VirtualDeviceResponse publicGatewayIp(String publicGatewayIp) {
    this.publicGatewayIp = publicGatewayIp;
    return this;
  }

   /**
   * Get publicGatewayIp
   * @return publicGatewayIp
  **/
  @ApiModelProperty(example = "149.97.198.94", value = "")
  public String getPublicGatewayIp() {
    return publicGatewayIp;
  }

  public void setPublicGatewayIp(String publicGatewayIp) {
    this.publicGatewayIp = publicGatewayIp;
  }

  public VirtualDeviceResponse primaryDnsName(String primaryDnsName) {
    this.primaryDnsName = primaryDnsName;
    return this;
  }

   /**
   * Get primaryDnsName
   * @return primaryDnsName
  **/
  @ApiModelProperty(example = "4.0.0.53", value = "")
  public String getPrimaryDnsName() {
    return primaryDnsName;
  }

  public void setPrimaryDnsName(String primaryDnsName) {
    this.primaryDnsName = primaryDnsName;
  }

  public VirtualDeviceResponse secondaryDnsName(String secondaryDnsName) {
    this.secondaryDnsName = secondaryDnsName;
    return this;
  }

   /**
   * Get secondaryDnsName
   * @return secondaryDnsName
  **/
  @ApiModelProperty(example = "129.250.35.250", value = "")
  public String getSecondaryDnsName() {
    return secondaryDnsName;
  }

  public void setSecondaryDnsName(String secondaryDnsName) {
    this.secondaryDnsName = secondaryDnsName;
  }

  public VirtualDeviceResponse termLength(String termLength) {
    this.termLength = termLength;
    return this;
  }

   /**
   * Get termLength
   * @return termLength
  **/
  @ApiModelProperty(example = "12", value = "")
  public String getTermLength() {
    return termLength;
  }

  public void setTermLength(String termLength) {
    this.termLength = termLength;
  }

  public VirtualDeviceResponse additionalBandwidth(String additionalBandwidth) {
    this.additionalBandwidth = additionalBandwidth;
    return this;
  }

   /**
   * Get additionalBandwidth
   * @return additionalBandwidth
  **/
  @ApiModelProperty(example = "200", value = "")
  public String getAdditionalBandwidth() {
    return additionalBandwidth;
  }

  public void setAdditionalBandwidth(String additionalBandwidth) {
    this.additionalBandwidth = additionalBandwidth;
  }

  public VirtualDeviceResponse siteId(String siteId) {
    this.siteId = siteId;
    return this;
  }

   /**
   * Get siteId
   * @return siteId
  **/
  @ApiModelProperty(example = "12345", value = "")
  public String getSiteId() {
    return siteId;
  }

  public void setSiteId(String siteId) {
    this.siteId = siteId;
  }

  public VirtualDeviceResponse systemIpAddress(String systemIpAddress) {
    this.systemIpAddress = systemIpAddress;
    return this;
  }

   /**
   * Get systemIpAddress
   * @return systemIpAddress
  **/
  @ApiModelProperty(example = "192.168.2.5", value = "")
  public String getSystemIpAddress() {
    return systemIpAddress;
  }

  public void setSystemIpAddress(String systemIpAddress) {
    this.systemIpAddress = systemIpAddress;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    VirtualDeviceResponse virtualDeviceResponse = (VirtualDeviceResponse) o;
    return Objects.equals(this.accountName, virtualDeviceResponse.accountName) &&
        Objects.equals(this.accountNumber, virtualDeviceResponse.accountNumber) &&
        Objects.equals(this.createdBy, virtualDeviceResponse.createdBy) &&
        Objects.equals(this.createdDate, virtualDeviceResponse.createdDate) &&
        Objects.equals(this.deviceSerialNo, virtualDeviceResponse.deviceSerialNo) &&
        Objects.equals(this.deviceTypeCategory, virtualDeviceResponse.deviceTypeCategory) &&
        Objects.equals(this.deviceTypeCode, virtualDeviceResponse.deviceTypeCode) &&
        Objects.equals(this.deviceTypeName, virtualDeviceResponse.deviceTypeName) &&
        Objects.equals(this.expiry, virtualDeviceResponse.expiry) &&
        Objects.equals(this.region, virtualDeviceResponse.region) &&
        Objects.equals(this.deviceTypeVendor, virtualDeviceResponse.deviceTypeVendor) &&
        Objects.equals(this.hostName, virtualDeviceResponse.hostName) &&
        Objects.equals(this.id, virtualDeviceResponse.id) &&
        Objects.equals(this.lastUpdatedBy, virtualDeviceResponse.lastUpdatedBy) &&
        Objects.equals(this.lastUpdatedDate, virtualDeviceResponse.lastUpdatedDate) &&
        Objects.equals(this.licenseFileId, virtualDeviceResponse.licenseFileId) &&
        Objects.equals(this.licenseName, virtualDeviceResponse.licenseName) &&
        Objects.equals(this.licenseStatus, virtualDeviceResponse.licenseStatus) &&
        Objects.equals(this.licenseType, virtualDeviceResponse.licenseType) &&
        Objects.equals(this.metroCode, virtualDeviceResponse.metroCode) &&
        Objects.equals(this.metroName, virtualDeviceResponse.metroName) &&
        Objects.equals(this.name, virtualDeviceResponse.name) &&
        Objects.equals(this.notifications, virtualDeviceResponse.notifications) &&
        Objects.equals(this.packageCode, virtualDeviceResponse.packageCode) &&
        Objects.equals(this.packageName, virtualDeviceResponse.packageName) &&
        Objects.equals(this.purchaseOrderNumber, virtualDeviceResponse.purchaseOrderNumber) &&
        Objects.equals(this.redundancyType, virtualDeviceResponse.redundancyType) &&
        Objects.equals(this.redundantUUID, virtualDeviceResponse.redundantUUID) &&
        Objects.equals(this.sshIpAddress, virtualDeviceResponse.sshIpAddress) &&
        Objects.equals(this.sshIpFqdn, virtualDeviceResponse.sshIpFqdn) &&
        Objects.equals(this.sshUsername, virtualDeviceResponse.sshUsername) &&
        Objects.equals(this.status, virtualDeviceResponse.status) &&
        Objects.equals(this.tenantName, virtualDeviceResponse.tenantName) &&
        Objects.equals(this.throughput, virtualDeviceResponse.throughput) &&
        Objects.equals(this.throughputUnit, virtualDeviceResponse.throughputUnit) &&
        Objects.equals(this.sshAcl, virtualDeviceResponse.sshAcl) &&
        Objects.equals(this.managementIp, virtualDeviceResponse.managementIp) &&
        Objects.equals(this.managementGatewayIp, virtualDeviceResponse.managementGatewayIp) &&
        Objects.equals(this.publicIp, virtualDeviceResponse.publicIp) &&
        Objects.equals(this.publicGatewayIp, virtualDeviceResponse.publicGatewayIp) &&
        Objects.equals(this.primaryDnsName, virtualDeviceResponse.primaryDnsName) &&
        Objects.equals(this.secondaryDnsName, virtualDeviceResponse.secondaryDnsName) &&
        Objects.equals(this.termLength, virtualDeviceResponse.termLength) &&
        Objects.equals(this.additionalBandwidth, virtualDeviceResponse.additionalBandwidth) &&
        Objects.equals(this.siteId, virtualDeviceResponse.siteId) &&
        Objects.equals(this.systemIpAddress, virtualDeviceResponse.systemIpAddress);
  }

  @Override
  public int hashCode() {
    return Objects.hash(accountName, accountNumber, createdBy, createdDate, deviceSerialNo, deviceTypeCategory, deviceTypeCode, deviceTypeName, expiry, region, deviceTypeVendor, hostName, id, lastUpdatedBy, lastUpdatedDate, licenseFileId, licenseName, licenseStatus, licenseType, metroCode, metroName, name, notifications, packageCode, packageName, purchaseOrderNumber, redundancyType, redundantUUID, sshIpAddress, sshIpFqdn, sshUsername, status, tenantName, throughput, throughputUnit, sshAcl, managementIp, managementGatewayIp, publicIp, publicGatewayIp, primaryDnsName, secondaryDnsName, termLength, additionalBandwidth, siteId, systemIpAddress);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class VirtualDeviceResponse {\n");
    
    sb.append("    accountName: ").append(toIndentedString(accountName)).append("\n");
    sb.append("    accountNumber: ").append(toIndentedString(accountNumber)).append("\n");
    sb.append("    createdBy: ").append(toIndentedString(createdBy)).append("\n");
    sb.append("    createdDate: ").append(toIndentedString(createdDate)).append("\n");
    sb.append("    deviceSerialNo: ").append(toIndentedString(deviceSerialNo)).append("\n");
    sb.append("    deviceTypeCategory: ").append(toIndentedString(deviceTypeCategory)).append("\n");
    sb.append("    deviceTypeCode: ").append(toIndentedString(deviceTypeCode)).append("\n");
    sb.append("    deviceTypeName: ").append(toIndentedString(deviceTypeName)).append("\n");
    sb.append("    expiry: ").append(toIndentedString(expiry)).append("\n");
    sb.append("    region: ").append(toIndentedString(region)).append("\n");
    sb.append("    deviceTypeVendor: ").append(toIndentedString(deviceTypeVendor)).append("\n");
    sb.append("    hostName: ").append(toIndentedString(hostName)).append("\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    lastUpdatedBy: ").append(toIndentedString(lastUpdatedBy)).append("\n");
    sb.append("    lastUpdatedDate: ").append(toIndentedString(lastUpdatedDate)).append("\n");
    sb.append("    licenseFileId: ").append(toIndentedString(licenseFileId)).append("\n");
    sb.append("    licenseName: ").append(toIndentedString(licenseName)).append("\n");
    sb.append("    licenseStatus: ").append(toIndentedString(licenseStatus)).append("\n");
    sb.append("    licenseType: ").append(toIndentedString(licenseType)).append("\n");
    sb.append("    metroCode: ").append(toIndentedString(metroCode)).append("\n");
    sb.append("    metroName: ").append(toIndentedString(metroName)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    notifications: ").append(toIndentedString(notifications)).append("\n");
    sb.append("    packageCode: ").append(toIndentedString(packageCode)).append("\n");
    sb.append("    packageName: ").append(toIndentedString(packageName)).append("\n");
    sb.append("    purchaseOrderNumber: ").append(toIndentedString(purchaseOrderNumber)).append("\n");
    sb.append("    redundancyType: ").append(toIndentedString(redundancyType)).append("\n");
    sb.append("    redundantUUID: ").append(toIndentedString(redundantUUID)).append("\n");
    sb.append("    sshIpAddress: ").append(toIndentedString(sshIpAddress)).append("\n");
    sb.append("    sshIpFqdn: ").append(toIndentedString(sshIpFqdn)).append("\n");
    sb.append("    sshUsername: ").append(toIndentedString(sshUsername)).append("\n");
    sb.append("    status: ").append(toIndentedString(status)).append("\n");
    sb.append("    tenantName: ").append(toIndentedString(tenantName)).append("\n");
    sb.append("    throughput: ").append(toIndentedString(throughput)).append("\n");
    sb.append("    throughputUnit: ").append(toIndentedString(throughputUnit)).append("\n");
    sb.append("    sshAcl: ").append(toIndentedString(sshAcl)).append("\n");
    sb.append("    managementIp: ").append(toIndentedString(managementIp)).append("\n");
    sb.append("    managementGatewayIp: ").append(toIndentedString(managementGatewayIp)).append("\n");
    sb.append("    publicIp: ").append(toIndentedString(publicIp)).append("\n");
    sb.append("    publicGatewayIp: ").append(toIndentedString(publicGatewayIp)).append("\n");
    sb.append("    primaryDnsName: ").append(toIndentedString(primaryDnsName)).append("\n");
    sb.append("    secondaryDnsName: ").append(toIndentedString(secondaryDnsName)).append("\n");
    sb.append("    termLength: ").append(toIndentedString(termLength)).append("\n");
    sb.append("    additionalBandwidth: ").append(toIndentedString(additionalBandwidth)).append("\n");
    sb.append("    siteId: ").append(toIndentedString(siteId)).append("\n");
    sb.append("    systemIpAddress: ").append(toIndentedString(systemIpAddress)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

