/*
 * Network Edge APIs
 * API Documentation for NE's Beta APIs. More information about Network Edge marketplace & NE platform can be found [here](https://ecxfabric-documentation.equinix.com/hc/en-us/articles/360021809172-Enterprise-Network-Edge-Beta-Program-Introduction).
 *
 * OpenAPI spec version: General Availability
 * Contact: Network-Edge-Support@equinix.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.equinix.networkedge.model;

import java.util.Objects;

import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModelProperty;

/**
 * VpnRequest
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2019-06-20T13:45:54.773-07:00")
public class VpnRequest {
  @SerializedName("configName")
  private String configName = null;

  @SerializedName("peerIp")
  private String peerIp = null;

  @SerializedName("peerSharedKey")
  private String peerSharedKey = null;

  @SerializedName("remoteAsn")
  private Long remoteAsn = null;

  @SerializedName("remoteIpAddress")
  private String remoteIpAddress = null;

  @SerializedName("password")
  private String password = null;

  @SerializedName("localAsn")
  private Long localAsn = null;

  @SerializedName("tunnelIp")
  private String tunnelIp = null;

  public VpnRequest configName(String configName) {
    this.configName = configName;
    return this;
  }

   /**
   * Get configName
   * @return configName
  **/
  @ApiModelProperty(example = "Traffic from AWS cloud", value = "")
  public String getConfigName() {
    return configName;
  }

  public void setConfigName(String configName) {
    this.configName = configName;
  }

  public VpnRequest peerIp(String peerIp) {
    this.peerIp = peerIp;
    return this;
  }

   /**
   * Get peerIp
   * @return peerIp
  **/
  @ApiModelProperty(example = "110.11.12.222", required = true, value = "")
  public String getPeerIp() {
    return peerIp;
  }

  public void setPeerIp(String peerIp) {
    this.peerIp = peerIp;
  }

  public VpnRequest peerSharedKey(String peerSharedKey) {
    this.peerSharedKey = peerSharedKey;
    return this;
  }

   /**
   * Get peerSharedKey
   * @return peerSharedKey
  **/
  @ApiModelProperty(example = "5bb2424e888bd", required = true, value = "")
  public String getPeerSharedKey() {
    return peerSharedKey;
  }

  public void setPeerSharedKey(String peerSharedKey) {
    this.peerSharedKey = peerSharedKey;
  }

  public VpnRequest remoteAsn(Long remoteAsn) {
    this.remoteAsn = remoteAsn;
    return this;
  }

   /**
   * Remote Customer ASN - Customer side
   * @return remoteAsn
  **/
  @ApiModelProperty(example = "65413", required = true, value = "Remote Customer ASN - Customer side")
  public Long getRemoteAsn() {
    return remoteAsn;
  }

  public void setRemoteAsn(Long remoteAsn) {
    this.remoteAsn = remoteAsn;
  }

  public VpnRequest remoteIpAddress(String remoteIpAddress) {
    this.remoteIpAddress = remoteIpAddress;
    return this;
  }

   /**
   * Remote Customer IP Address - Customer side
   * @return remoteIpAddress
  **/
  @ApiModelProperty(example = "100.210.1.31", required = true, value = "Remote Customer IP Address - Customer side")
  public String getRemoteIpAddress() {
    return remoteIpAddress;
  }

  public void setRemoteIpAddress(String remoteIpAddress) {
    this.remoteIpAddress = remoteIpAddress;
  }

  public VpnRequest password(String password) {
    this.password = password;
    return this;
  }

   /**
   * BGP Password
   * @return password
  **/
  @ApiModelProperty(example = "pass123", required = true, value = "BGP Password")
  public String getPassword() {
    return password;
  }

  public void setPassword(String password) {
    this.password = password;
  }

  public VpnRequest localAsn(Long localAsn) {
    this.localAsn = localAsn;
    return this;
  }

   /**
   * Local ASN - Equinix side
   * @return localAsn
  **/
  @ApiModelProperty(example = "65414", value = "Local ASN - Equinix side")
  public Long getLocalAsn() {
    return localAsn;
  }

  public void setLocalAsn(Long localAsn) {
    this.localAsn = localAsn;
  }

  public VpnRequest tunnelIp(String tunnelIp) {
    this.tunnelIp = tunnelIp;
    return this;
  }

   /**
   * Local Tunnel IP Address in CIDR format
   * @return tunnelIp
  **/
  @ApiModelProperty(example = "192.168.7.2/30", required = true, value = "Local Tunnel IP Address in CIDR format")
  public String getTunnelIp() {
    return tunnelIp;
  }

  public void setTunnelIp(String tunnelIp) {
    this.tunnelIp = tunnelIp;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    VpnRequest vpnRequest = (VpnRequest) o;
    return Objects.equals(this.configName, vpnRequest.configName) &&
        Objects.equals(this.peerIp, vpnRequest.peerIp) &&
        Objects.equals(this.peerSharedKey, vpnRequest.peerSharedKey) &&
        Objects.equals(this.remoteAsn, vpnRequest.remoteAsn) &&
        Objects.equals(this.remoteIpAddress, vpnRequest.remoteIpAddress) &&
        Objects.equals(this.password, vpnRequest.password) &&
        Objects.equals(this.localAsn, vpnRequest.localAsn) &&
        Objects.equals(this.tunnelIp, vpnRequest.tunnelIp);
  }

  @Override
  public int hashCode() {
    return Objects.hash(configName, peerIp, peerSharedKey, remoteAsn, remoteIpAddress, password, localAsn, tunnelIp);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class VpnRequest {\n");
    
    sb.append("    configName: ").append(toIndentedString(configName)).append("\n");
    sb.append("    peerIp: ").append(toIndentedString(peerIp)).append("\n");
    sb.append("    peerSharedKey: ").append(toIndentedString(peerSharedKey)).append("\n");
    sb.append("    remoteAsn: ").append(toIndentedString(remoteAsn)).append("\n");
    sb.append("    remoteIpAddress: ").append(toIndentedString(remoteIpAddress)).append("\n");
    sb.append("    password: ").append(toIndentedString(password)).append("\n");
    sb.append("    localAsn: ").append(toIndentedString(localAsn)).append("\n");
    sb.append("    tunnelIp: ").append(toIndentedString(tunnelIp)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

